### ISSUE TITLE
AttributeError thrown by ilab diff on yaml that is just a list

### ISSUE THREAD

**Issue by markstur** [instructlab/instructlab#1170]
**Describe the bug**

Old/invalid yaml throws an AttributeError instead of a more appropriate error.

**To Reproduce**
1. Copy this old one: /Users/markstur/gh/instructlab/test_run_XXXXXXXX.taa3Yg9enz/taxonomy/compositional_skills/writing/freeform/jokes/puns/testrun_qna.yaml
2. run `ilab diff`
3. See error

**Expected behavior**
Either a usable validation error or a default version (missing version) handled.

**Screenshots**
(venv) markstur@Marks-MacBook-Pro test_run_XXXXXXXX.taa3Yg9enz % ilab diff
compositional_skills/writing/freeform/jokes/puns/testrun_qna.yaml
compositional_skills/writing/freeform/jokes/puns/qna.yaml
Traceback (most recent call last):
  File "/Users/markstur/gh/instructlab/test_run_XXXXXXXX.taa3Yg9enz/venv/lib/python3.9/site-packages/instructlab/utils.py", line 437, in read_taxonomy_file
    version = get_version(contents)
  File "/Users/markstur/gh/instructlab/test_run_XXXXXXXX.taa3Yg9enz/venv/lib/python3.9/site-packages/instructlab/utils.py", line 398, in get_version
    version = contents.get("version", 1)
AttributeError: 'list' object has no attribute 'get'

**Device Info (please complete the following information):**
 - Hardware Specs: [e.g. Apple M2 Pro Chip, 16 GB Memory, etc.]
 - OS Version: [e.g. Mac OS 14.4.1, Fedora Linux 40]
 - Python Version: [output of `python --version`]
 - InstructLab Version: [output of `ilab --version`]
Mac M3 ilab 0.15.1.dev7

**Additional context**
Notice the yaml is valid but it is just a list so it fails when code assumes it is a map.

**Comment by bjhargrave** [comment]
What is the yaml file used here? Perhaps you can attach it?
