### ISSUE TITLE
help command in chat console hit error

### ISSUE THREAD

**Issue by chudegao** [instructlab/instructlab#1236]
```
(dlipy3) [root@llm opt]# ilab chat -gm
DEBUG 2024-05-31 05:02:43,254 server.py:63 Trying to connect to http://127.0.0.1:8000/v1...
DEBUG 2024-05-31 05:02:45,737 server.py:81 Trying port 58166...
DEBUG 2024-05-31 05:02:45,737 server.py:101 Port 58166 is available.
DEBUG 2024-05-31 05:02:45,737 server.py:105 Connection to http://127.0.0.1:8000/v1 failed. Starting a temporary server at http://127.0.0.1:58166/v1 with model_path models/merlinite-7b-lab-Q4_K_M.gguf...
=========greedy_mode: True
╭──────────────────────────────────────────────────── system ────────────────────────────────────────────────────╮
│ Welcome to InstructLab Chat w/ MERLINITE-7B-LAB-Q4_K_M (type /h for help)                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
>>> INFO 2024-05-31 05:02:47,732 server.py:206 Starting server process, press CTRL+C to shutdown server...default]
INFO 2024-05-31 05:02:47,732 server.py:207 After application startup complete see http://127.0.0.1:58166/docs for API.
>>>                                                                                                   [S][default]
>>> /s save.log                                                                                       [S][default]
>>> /h                                                                                                [S][default]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/dlipy3/bin/ilab", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/instructlab/lab.py", line 764, in chat
    chat_cli(
  File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/instructlab/chat/chat.py", line 563, in chat_cli
    ccb.start_prompt(logger)
  File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/instructlab/chat/chat.py", line 346, in start_prompt
    handler(content)
TypeError: ConsoleChatBot._handle_help() takes 1 positional argument but 2 were given
(dlipy3) [root@llm opt]# 
```

**Comment by nathan-weinberg** [comment]
Fixed by #1237
