### ISSUE TITLE
Failed to initialize metal backend

### ISSUE THREAD

**Issue by anniedoris** [instructlab/instructlab#1262]
**Describe the bug**
When I run ```ilab serve,``` I'm seeing the following error:

```
ERROR 2024-06-04 14:35:12,627 llama_cpp:0 llama_new_context_with_model: failed to initialize Metal backend
ERROR 2024-06-04 14:35:12,629 llama_cpp:0 Traceback (most recent call last):
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/instructlab/server.py", line 165, in server
    app = create_app(settings=settings)
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/llama_cpp/server/app.py", line 147, in create_app
    set_llama_proxy(model_settings=model_settings)
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/llama_cpp/server/app.py", line 68, in set_llama_proxy
    _llama_proxy = LlamaProxy(models=model_settings)
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/llama_cpp/server/model.py", line 31, in __init__
    self._current_model = self.load_llama_from_model_settings(
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/llama_cpp/server/model.py", line 217, in load_llama_from_model_settings
    _model = create_fn(
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/llama_cpp/llama.py", line 352, in __init__
    self._ctx = _LlamaContext(
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/llama_cpp/_internals.py", line 267, in __init__
    raise ValueError("Failed to create llama_context")
ValueError: Failed to create llama_context

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/instructlab/lab.py", line 347, in serve
    server(
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/instructlab/server.py", line 178, in server
    raise ServerException(f"failed creating the server application: {exc}") from exc
instructlab.server.ServerException: failed creating the server application: Failed to create llama_context

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/annie/opt/anaconda3/envs/ilab/bin/ilab", line 8, in <module>
    sys.exit(cli())
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/instructlab/lab.py", line 358, in serve
    click.secho(f"Error creating server: {exc}", fg="red")
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/click/termui.py", line 634, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
  File "/Users/annie/opt/anaconda3/envs/ilab/lib/python3.9/site-packages/click/_compat.py", line 99, in __getattr__
    return getattr(self._stream, name)
AttributeError: 'str' object has no attribute 'write'
```

I noticed that there was a [previous issue](https://github.com/instructlab/instructlab/issues/1138) that was somewhat similar. I tried to run the suggestion posted there:

```
pip cache remove llama_cpp_python
pip install --force-reinstall 'llama_cpp_python[server]==0.2.55' -C cmake.args="-DLLAMA_METAL=on;-DCMAKE_OSX_ARCHITECTURES=arm64;-DCMAKE_APPLE_SILICON_PROCESSOR=arm64"
```
But 0.2.55 seems to be the wrong version (it throws an error about the version once I try running ```ilab serve``` again). Do you have any suggestions for how to resolve this issue? I am running everything from a conda environment which is using Python version 3.9.13.

**To Reproduce**
```ilab serve``` and see device info

**Device Info (please complete the following information):**
 - Hardware Specs: Apple M2 Max, 64 GB Memory
 - OS Version: Mac OS 14.5
 - Python Version: 3.9.13
 - InstructLab Version: 0.16.0

**Comment by bjhargrave** [comment]
We are now using llama_cpp_python 0.2.75. See https://github.com/instructlab/instructlab/discussions/1148

**Comment by anniedoris** [comment]
Thanks for the reply! I tried that, but I'm seeing this error:

```
RuntimeError: Failed to load shared library '/Users/annie/opt/anaconda3/envs/ilab/lib/python3.11/site-packages/llama_cpp/libllama.dylib': dlopen(/Users/annie/opt/anaconda3/envs/ilab/lib/python3.11/site-packages/llama_cpp/libllama.dylib, 0x0006): tried: '/Users/annie/opt/anaconda3/envs/ilab/lib/python3.11/site-packages/llama_cpp/libllama.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/annie/opt/anaconda3/envs/ilab/lib/python3.11/site-packages/llama_cpp/libllama.dylib' (no such file), '/Users/annie/opt/anaconda3/envs/ilab/lib/python3.11/site-packages/llama_cpp/libllama.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Comment by tiran** [comment]
pip is caching locally built wheels. Please purge the cache with `pip cache remove llama_cpp_python` and try again.

**Comment by bjhargrave** [comment]
> (have 'arm64', need 'x86_64'))

This sounds like you are running an x86_64 version Python on your arm64 mac under Rosetta emulation. 

Above you reported:

> * Hardware Specs: Apple M2 Max, 64 GB Memory

What does `file -b $(command -v python)` report?

**Comment by anniedoris** [comment]
`file -b $(command -v python)` does return `Mach-O 64-bit executable x86_64`. What would you recommend that I do in that case?

**Comment by bjhargrave** [comment]
You need to uninstall that python command and reinstall to get the proper arm64 version. I don't know how you installed your python. If you used brew and migrated from a x86_64 mac, then you may also still be running an x86_64 version of brew which you will also need to uninstall and install the arm64 version.

In any case, I don't think this issue is a bug in instructlab, so I am going to close it. You can follow up with any other usage questions in the project slack or users mail list. https://github.com/instructlab/community/blob/main/Collaboration.md#chat

**Comment by anniedoris** [comment]
Thanks for your help. I updated brew and python and it's working now :)
