### ISSUE TITLE
instructlab shouldn't stack trace when it can't connect to the server

### ISSUE THREAD

**Issue by paulczar** [instructlab/instructlab#1310]
**Describe the bug**

If you try and connect to a server that doesn't exist (or isn't listening) you'll lose the error in the stack trace.

**To Reproduce**

1. Run

```
$ ilab chat -m models/ggml-model-f16.gguf
```

output

```
Traceback (most recent call last):
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 952, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/instruct/instructlab/venv/bin/ilab", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/instructlab/lab.py", line 758, in chat
    chat_cli(
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/instructlab/chat/chat.py", line 486, in chat_cli
    model_list = client.models.list().data
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/openai/resources/models.py", line 80, in list
    return self._get_api_list(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 1289, in get_api_list
    return self._request_api_list(model, page, opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 1134, in _request_api_list
    return self.request(page, options, stream=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 976, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 976, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/instruct/instructlab/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 986, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
```

**Expected behavior**

It should just output something simple and useful like

```
Connection refused
```

**Comment by leseb** [comment]
@liranr23 is working on this. Next time please leave a comment saying that you're picking it up, thanks!

**Comment by makelinux** [comment]
I have a  better solution.
