### ISSUE TITLE
v0.17.0 ilab convert no longer works and throws an error 404 to huggingface

### ISSUE THREAD

**Issue by gshipley** [instructlab/instructlab#1375]
**Describe the bug**
It appears with ilab v0.17.0 that ilab convert no longer works

**To Reproduce**
1: ilab generate
2: ilab trian
3: ilab convert

Give the following error message:
 ilab model convert
Loading pretrained model
Traceback (most recent call last):
  File "/Users/gshipley/demo/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/Users/gshipley/demo/venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/instructlab-merlinite-7b-lab-mlx-q/revision/main

**Expected behavior**
a quantized version of the model is created

**Device Info (please complete the following information):**
nstructlab.version: 0.17.0
sys.version: 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.platform: darwin
os.name: posix
platform.release: 23.5.0
platform.machine: arm64
torch.version: 2.3.1
torch.backends.cpu.capability: NO AVX
torch.version.cuda: None
torch.version.hip: None
torch.cuda.available: False
torch.backends.cuda.is_built: False
torch.backends.mps.is_built: True
torch.backends.mps.is_available: True
llama_cpp_python.version: 0.2.75
llama_cpp_python.supports_gpu_offload: True

**Comment by cdoern** [comment]
It's possible this was due to the code shuffle. This is first on my list for the week

**Comment by nathan-weinberg** [comment]
@gshipley this still an issue with `0.17.1`?

**Comment by mikebski** [comment]
@nathan-weinberg  - Yes, this is still an issue

**Comment by bjhargrave** [comment]
I just ran `ilab model convert` from HEAD on my M3 Mac without issue. So HEAD seems to be fine.

**Comment by jaideepr97** [comment]
can confirm I was unable to reproduce it on the main branch, but did manage to reproduce it on v0.17.1
looking into it now

**Comment by sshaaf** [comment]
I ran v0.17.1 on m3, and unable to reproduce it.

**Comment by joefern1** [comment]
I encountered the same issue with iLab model convert on v0.17.1 which I just downloaded and tested:

(venv) joefern-m1@joes-mbp instructlab % ilab model convert
Loading pretrained model
Failed to fine tune: 401 Client Error. (Request ID: Root=1-66951a4e-794fae16439402ed03a22770;04cfc62b-7c53-46b3-9fe7-ddcab9c79802)

Repository Not Found for url: https://huggingface.co/api/models/instructlab-merlinite-7b-lab-mlx-q/revision/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
(venv) joefern-m1@joes-mbp instructlab % ilab --version
ilab, version 0.17.1

**Comment by jaideepr97** [comment]
slight update:
I was initially able to reproduce this issue when I switched branches (from main to 0.17.1) mid-workflow 
however, since then I've executed the workflow end to end from fresh clone to training and serving a model on the 0.17.1 branch multiple times and have been unable to reproduce the issue again

**Comment by nathan-weinberg** [comment]
0.17.1 is pretty old at this point relative to the development process - we're hoping to release an 0.18.0 this week which has a ton of work in it, so it's worth waiting for that release to see if this bug persists IMHO

**Comment by lesliejrodrig** [comment]
I've encountered this issue in 0.17.1 as well. Just for future reference I can reproduce this on my M2 when I execute ilab convert and run out of storage space. After clearing up some space and trying the ilab convert command again, I see this error

**Comment by gnthaker** [comment]
I am also facing the same on M3 as well, I have tried today as well.

**Comment by jaideepr97** [comment]
could everyone experiencing this still. try it with `v0.18.2`? 
If this is still happening then we can re-title the issue so it's not `0.17` specific. If it is not reproducible I might suggest that people consider upgrading to 0.18 and close this issue - This project has been though a lot of changes since v0.17 anyway

**Comment by jaideepr97** [comment]
@gshipley given that 0.17 is pretty old at this point, would you be okay with closing this issue?
