### ISSUE TITLE
"ilab model convert" stack traces when invalid repo ID 

### ISSUE THREAD

**Issue by leseb** [instructlab/instructlab#1385]
```
ilab model convert --model-dir ./instructlab-merlinite-7b-lab-mlx
Loading pretrained model
Traceback (most recent call last):
  File "/Users/leseb/Documents/AI/instructlab/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/instructlab/utils.py", line 60, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/instructlab/model/convert.py", line 69, in convert
    fine_tune(
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/instructlab/train/lora_mlx/fuse.py", line 29, in fine_tune
    loaded_model, tokenizer, config = utils.load(model)
                                      ^^^^^^^^^^^^^^^^^
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/instructlab/train/lora_mlx/utils.py", line 167, in load
    snapshot_download(
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: './instructlab-merlinite-7b-lab-mlx'.
```

**Comment by leseb** [comment]
Fixed in https://github.com/instructlab/instructlab/pull/1384
