### ISSUE TITLE
 "ilab convert" failed at "TypeError: 'module' object is not callable. Did you mean: 'glob.glob(...)'?"

### ISSUE THREAD

**Issue by koalakangaroo** [instructlab/instructlab#1388]
**Describe the bug**
 "ilab convert" failed at "TypeError: 'module' object is not callable. Did you mean: 'glob.glob(...)'?" 

**To Reproduce**
Steps to reproduce the behavior (with Apple M3 Pro):
1. Execute "ilab train" successfully ("instructlab-merlinite-7b-lab-mlx-q" directory is created)
2. Execute "ilab convert" which failed at "TypeError: 'module' object is not callable. Did you mean: 'glob.glob(...)'?"

Wrote instructlab-merlinite-7b-lab-trained/instructlab-merlinite-7b-lab.gguf
INFO 2024-06-17 18:07:39,030 convert.py:93: convert deleting safetensors files from instructlab-merlinite-7b-lab-trained...
Traceback (most recent call last):
  File "/Users/testuser/LLM/instructlab/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/Users/testuser/LLM/instructlab/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/testuser/LLM/instructlab/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/testuser/LLM/instructlab/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/testuser/LLM/instructlab/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/testuser/LLM/instructlab/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/testuser/LLM/instructlab/venv/lib/python3.12/site-packages/instructlab/utils.py", line 60, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/testuser/LLM/instructlab/venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/testuser/LLM/instructlab/venv/lib/python3.12/site-packages/instructlab/model/convert.py", line 94, in convert
    for file in glob(os.path.join(model_dir_fused_pt, "*.safetensors")):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Expected behavior**
The command executes successfully and the trained model is created.

**Device Info (please complete the following information):**
 - Hardware Specs: Apple M3 Pro
 - OS Version: Mac OS Sonoma 14.5
 - Python Version: Python 3.12.3
 - InstructLab Version: ilab, version 0.17.0

**Additional context**

**Comment by leseb** [comment]
Dup of https://github.com/instructlab/instructlab/issues/1371, so closing, feel free to re-open if you have any concerns. Thanks!
