### ISSUE TITLE
iLab fails on Python 3.12.4 ; 3.12.3 is ok.

### ISSUE THREAD

**Issue by pilhuhn** [instructlab/instructlab#1391]
**Describe the bug**

❯ python version
/opt/homebrew/Cellar/python@3.12/3.12.4

```
❯ ilab serve
Traceback (most recent call last):
  File "/Users/hrupp/instructlab/venv/bin/ilab", line 5, in <module>
    from instructlab.lab import ilab
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/instructlab/lab.py", line 18, in <module>
    from .config import config as config_group
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/instructlab/config/config.py", line 8, in <module>
    from .init import init
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/instructlab/config/init.py", line 13, in <module>
    from instructlab import utils
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/instructlab/utils.py", line 19, in <module>
    from langchain_text_splitters import RecursiveCharacterTextSplitter
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/langchain_text_splitters/__init__.py", line 22, in <module>
    from langchain_text_splitters.base import (
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/langchain_text_splitters/base.py", line 23, in <module>
    from langchain_core.documents import BaseDocumentTransformer, Document
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/langchain_core/documents/__init__.py", line 6, in <module>
    from langchain_core.documents.compressor import BaseDocumentCompressor
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/langchain_core/documents/compressor.py", line 6, in <module>
    from langchain_core.callbacks import Callbacks
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/langchain_core/callbacks/__init__.py", line 22, in <module>
    from langchain_core.callbacks.manager import (
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/langchain_core/callbacks/manager.py", line 29, in <module>
    from langsmith.run_helpers import get_run_tree_context
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/langsmith/run_helpers.py", line 38, in <module>
    from langsmith import client as ls_client
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/langsmith/client.py", line 52, in <module>
    from langsmith import env as ls_env
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/langsmith/env/__init__.py", line 3, in <module>
    from langsmith.env._runtime_env import (
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/langsmith/env/_runtime_env.py", line 9, in <module>
    from langsmith.utils import get_docker_compose_command
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/langsmith/utils.py", line 29, in <module>
    from langsmith import schemas as ls_schemas
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/langsmith/schemas.py", line 69, in <module>
    class Example(ExampleBase):
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/pydantic/v1/main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/pydantic/v1/main.py", line 807, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/pydantic/v1/typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/pydantic/v1/typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hrupp/instructlab/venv/lib/python3.12/site-packages/pydantic/v1/typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```

This looks like https://github.com/pydantic/pydantic/issues/9637 

**To Reproduce**

Run any iLab comman on Python 3.12.4

**Expected behavior**

It works (to some degree) and does not exit via exception

**Device Info (please complete the following information):**

M3 mac

❯ python --version
Python 3.12.4

```
❯ ilab --version
Traceback (most recent call last):
  File "/Users/hrupp/instructlab/venv/bin/ilab", line 5, in <module>
    from instructlab.lab import ilab
....
```

**Additional context**

This was an in-place upgrade from 0.16.1

**Comment by nathan-weinberg** [comment]
@pilhuhn In the issue you linked it looks like they released a subsequent version that fixed the problem - can you confirm which version of `pydantic` you have installed in your env?

**Comment by pilhuhn** [comment]
```
❯ ls  -d venv/lib/python3.12/site-packages/pydantic*
venv/lib/python3.12/site-packages/pydantic
venv/lib/python3.12/site-packages/pydantic-2.7.1.dist-info
venv/lib/python3.12/site-packages/pydantic_core
venv/lib/python3.12/site-packages/pydantic_core-2.18.2.dist-info
venv/lib/python3.12/site-packages/pydantic_settings
venv/lib/python3.12/site-packages/pydantic_settings-2.2.1.dist-info
venv/lib/python3.12/site-packages/pydantic_yaml
venv/lib/python3.12/site-packages/pydantic_yaml-1.3.0.dist-info
```

@nathan-weinberg If I knew how to surgically replace 2.7.1 with 2.7.4 to test I'd do so :)

**Comment by pilhuhn** [comment]
@nathan-weinberg Ah, I was rather thinking of only replacing the pydantic version :)  

Anyway: using 2.7.4 solves the issue. Bumping the minimum version would be good.
