### ISSUE TITLE
ilab convert broken in 0.17.0

### ISSUE THREAD

**Issue by jeffmaury** [instructlab/instructlab#1414]
**Describe the bug**

ilab convert throws an error and a stack trace
**To Reproduce**
1. `ilab generate`
2. `ilab train`
3. `ilab convert`

**Expected behavior**
No error raised

**Screenshots**
```
Wrote instructlab-merlinite-7b-lab-trained/instructlab-merlinite-7b-lab.gguf
INFO 2024-06-18 17:03:41,970 convert.py:93: convert deleting safetensors files from instructlab-merlinite-7b-lab-trained...
Traceback (most recent call last):
  File "/Users/jmaury/work/instruct-lab/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/Users/jmaury/work/instruct-lab/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmaury/work/instruct-lab/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/jmaury/work/instruct-lab/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmaury/work/instruct-lab/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmaury/work/instruct-lab/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmaury/work/instruct-lab/venv/lib/python3.12/site-packages/instructlab/utils.py", line 60, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmaury/work/instruct-lab/venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmaury/work/instruct-lab/venv/lib/python3.12/site-packages/instructlab/model/convert.py", line 94, in convert
    for file in glob(os.path.join(model_dir_fused_pt, "*.safetensors")):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'glob.glob(...)'?
(venv) jmaury@MacBook-Pro-de-Jeff instruct-lab % 


```**Device Info (please complete the following information):**
 - Hardware Specs: Apple M2 Pro Chip, 32 GB Memory
 - OS Version: Mac OS 14.5
 - Python Version: 3.12.1
 - InstructLab Version: 0.17.0

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by leseb** [comment]
Dup of https://github.com/instructlab/instructlab/issues/1371. The patch is already in https://github.com/instructlab/instructlab/tree/release-v0.17. 0.17.1 soon to be release @nathan-weinberg what's the timeline for this one? Thanks!

**Comment by nathan-weinberg** [comment]
@leseb No timeline in mind - I could do it today even!
