### ISSUE TITLE
Add vLLM functional test in CI

### ISSUE THREAD

**Issue by leseb** [instructlab/instructlab#1456]
While working on the addition of vLLM https://github.com/instructlab/instructlab/pull/1442, I tried adding func test to the e2e test since the runner has a CUDA GPU. Unfortunately, it does not have enough GPU memory. This is a Linux VM with a single Tesla T4 GPU.

I ended up with the following error:

```
ERROR 2024-06-25 12:52:41,612 serving_backend:0: flush [rank0]: Traceback (most recent call last):
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/bin/ilab", line 8, in <module>
[rank0]:     sys.exit(ilab())
[rank0]:              ^^^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
[rank0]:     return self.main(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
[rank0]:     rv = self.invoke(ctx)
[rank0]:          ^^^^^^^^^^^^^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
[rank0]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
[rank0]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
[rank0]:     return ctx.invoke(self.callback, **ctx.params)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
[rank0]:     return __callback(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
[rank0]:     return f(get_current_context(), *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/instructlab/utils.py", line 635, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/instructlab/model/serve.py", line 123, in serve
[rank0]:     backend_instance.run()
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/instructlab/model/backends/vllm.py", line 58, in run
[rank0]:     server(
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/instructlab/model/backends/vllm.py", line 142, in server
[rank0]:     engine = api_server.engine = AsyncLLMEngine.from_engine_args(
[rank0]:                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 398, in from_engine_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 349, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 473, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 236, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 326, in _initialize_kv_caches
[rank0]:     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/vllm/executor/gpu_executor.py", line 86, in initialize_cache
[rank0]:     self.driver_worker.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/vllm/worker/worker.py", line 195, in initialize_cache
[rank0]:     raise_if_cache_size_invalid(num_gpu_blocks,
[rank0]:   File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/vllm/worker/worker.py", line 378, in raise_if_cache_size_invalid
[rank0]:     raise ValueError("No available memory for the cache blocks. "
[rank0]: ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
```

I then tried using different flags like:

```
dtype="half",
enforce_eager=True,  # TODO: remove me. CI run into issue: see: https://github.com/vllm-project/vllm/issues/2248
tensor_parallel_size=1,  # TODO: remove me. CI run into issue: see: https://github.com/vllm-project/vllm/issues/2248
``` 

But that did not help.

Here is the test I added to `scripts/basic-workflow-tests.sh`:

```diff
commit 52f76f821b362aae225f904527bfd90692f3c26b
Author: Sébastien Han <seb@redhat.com>
Date:   Fri Jun 21 21:34:41 2024 +0200

    ci: add func test for vllm
    
    The e2e runner has all we need to run vLLM. So the e2e test has a small
    vLLM test that validates:
    
    * the backend starts correctly with `ilab model serve`
    * the client can chat with the server with `ilab model chat`
    * the client can chat with a temp server (when `ilab model serve`is not
      running and only `ilab model chat` was called)
    
    Signed-off-by: Sébastien Han <seb@redhat.com>

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
index b7010b0..6db5a5c 100644
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -107,7 +107,7 @@ jobs:
 
       - name: Install Packages
         run: |
-          sudo apt-get install -y cuda-toolkit git cmake build-essential virtualenv
+          sudo apt-get install -y cuda-toolkit git cmake build-essential virtualenv expect
           nvidia-smi
           ls -l /dev/nvidia*
 
diff --git a/scripts/basic-workflow-tests.sh b/scripts/basic-workflow-tests.sh
index 107bfec..7141512 100755
--- a/scripts/basic-workflow-tests.sh
+++ b/scripts/basic-workflow-tests.sh
@@ -23,6 +23,28 @@ BOLD='\033[1m'
 NC='\033[0m' # No Color
 
 SCRIPTDIR=$(dirname "$0")
+PID_SERVE=
+
+trap 'cleanup "$?"' EXIT QUIT INT TERM
+
+cleanup() {
+    set +e
+    if [ "${1:-0}" -ne 0 ]; then
+        printf "\n\n"
+        printf "\e[31m=%.0s\e[0m" {1..80}
+        printf "\n\e[31mERROR OCCURRED\e[0m\n"
+        printf "\e[31mFunction: %s\e[0m\n" "${FUNCNAME[1]}"
+        printf "\e[31mExit Code: %s\e[0m\n" "$1"
+        printf "\e[31m=%.0s\e[0m" {1..80}
+        printf "\n\n"
+    fi
+    if [ -n "$PID_SERVE" ]; then
+        kill "$PID_SERVE"
+        wait "$PID_SERVE"
+    fi
+    cat serve.log
+    set -e
+}
 
 step() {
     echo -e "$BOLD$* - $(date)$NC"
@@ -191,6 +213,60 @@ test_exec() {
     kill $PID
 }
 
+test_vllm_backend(){
+    task "Testing VLLM backend"
+    task "Downloading the model"
+    ilab download --repository instructlab/merlinite-7b-lab
+
+    ilab model serve --model-path models/instructlab/merlinite-7b-lab/ &> serve.log &
+    PID_SERVE=$!
+
+    wait_for_server
+
+    expect -c '
+        set timeout 120
+        spawn ilab chat
+        expect ">>>"
+        send "this is a test! what are you? do not exceed ten words in your reply.\r"
+        send "exit\r"
+        expect eof
+    '
+
+    kill $PID_SERVE
+    task "VLLM backend test passed for serve/chat"
+
+    task "Testing VLLM backend for chat only"
+
+    sed -i 's|models/merlinite-7b-lab-Q4_K_M.gguf|models/instructlab/merlinite-7b-lab/g' config.yaml
+    # shellcheck disable=SC2016
+    expect -c '
+        set timeout 20
+        spawn ilab chat --model models/instructlab/merlinite-7b-lab/
+        send "hello!\r"
+        send "exit\r"
+        expect {
+            "Traceback (most recent call last):" { set exp_result 1 }
+            default { set exp_result 0 }
+        }
+        if { $exp_result != 0 } {
+            puts stderr "Error: ilab chat command failed"
+            exit 1
+        }
+    '
+}
+
+wait_for_server(){
+    if ! timeout 120 bash -c '
+        until curl 127.0.0.1:8000|grep "{\"message\":\"Hello from InstructLab! Visit us at https://instructlab.ai\"}"; do
+            echo "waiting for server to start"
+            sleep 1
+        done
+    '; then
+        echo "server did not start"
+        exit 1
+    fi
+}
+
 usage() {
     echo "Usage: $0 [-m] [-h]"
     echo "  -m  Run minimal configuration (run quicker when you have no GPU)"
@@ -228,5 +304,7 @@ while getopts "cmgh" opt; do
     esac
 done
 
+ilab sysinfo
+test_vllm_backend
 set_defaults
 test_exec
diff --git a/src/instructlab/model/backends/vllm.py b/src/instructlab/model/backends/vllm.py
index f99f198..f61eb6c 100644
--- a/src/instructlab/model/backends/vllm.py
+++ b/src/instructlab/model/backends/vllm.py
@@ -134,6 +134,7 @@ def server(
     engine_args = AsyncEngineArgs(
         model=model_path,
         max_model_len=4096,  # TODO: make this configurable
+        dtype="half",  # TODO: this is hardcoded for the e2e test to pass, remove once we have extra flags
     )
 
     engine = api_server.engine = AsyncLLMEngine.from_engine_args(

```

We should revisit this if we ever get a more powerful runner.

**Comment by leseb** [comment]
https://github.com/instructlab/instructlab/actions/runs/9662539697/job/26652643014?pr=1442

**Comment by nathan-weinberg** [comment]
Might we be able to bump the size of the runner?

**Comment by leseb** [comment]
> Might we be able to bump the size of the runner?

It's a special runner, I'm not familiar with the env, @russellb knows more about it.

**Comment by russellb** [comment]
https://github.com/instructlab/instructlab/pull/1556 introduces the next size up. Once that's in, maybe we could just configure that job to use vllm instead of llama-cpp as its backend?  maybe a new script arg `-v` that enables vllm ...

**Comment by russellb** [comment]
> @russellb awesome! How is the job triggered at the moment?

once merged, manually only via the github UI - similar to how `e2e` worked at first before we enabled it to run on PRs automatically

**Comment by russellb** [comment]
We merged part of this but it’s not turned on in a CI workflow yet

**Comment by alimaredia** [comment]
https://github.com/instructlab/instructlab/pull/1801 addresses vLLM installation and enablement in the A10 workflows.
