### ISSUE TITLE
`tox` not working on Mac, `aspell` and `pyproject.toml` problems

### ISSUE THREAD

**Issue by JamesKunstle** [instructlab/instructlab#1464]
**Describe the bug**
Installed `ilab` from scratch, initialized properly, then tried to run `tox` after installing development requirements.

Got the error below. One error is missing `aspell.h` headerfile which doesn't exist on Mac, from reading some debugging information.

**Device Info (please complete the following information):**
 - Hardware Specs: [M1 Pro, 32GB RAM]
 - OS Version: [mac 14.5]
 - Python Version: [3.11`]
 - InstructLab Version: [0.17.1.dev103]

**Logs**

```
ruff: commands[0]> ./scripts/ruff.sh fix
RUN: 'ruff check --fix .'
All checks passed!

RUN: 'ruff format .'
62 files left unchanged

RUN: 'isort .'
Fixing /Users/jkunstle/Developer/github/instructlab/src/instructlab/_version.py
Skipped 5 files

ruff: OK ✔ in 1.04 seconds
lint: commands[0]> .tox/lint/bin/python -m pylint --load-plugins pylint_pydantic src/instructlab/ tests/


Report
======
1341 statements analysed.

Statistics by type
------------------

+---------+-------+-----------+-----------+------------+---------+
|type     |number |old number |difference |%documented |%badname |
+=========+=======+===========+===========+============+=========+
|module   |23     |23         |=          |4.35        |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|class    |23     |23         |=          |60.87       |8.70     |
+---------+-------+-----------+-----------+------------+---------+
|method   |78     |78         |=          |23.08       |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|function |59     |59         |=          |54.24       |0.00     |
+---------+-------+-----------+-----------+------------+---------+



External dependencies
---------------------
::

    click (src.instructlab.configuration,src.instructlab.lab,src.instructlab.utils,tests.test_lab)
      \-testing (tests.test_lab_diff,tests.test_lab_download,tests.test_lab_generate,tests.test_lab_init,tests.test_lab_train)
    git (src.instructlab.utils,tests.taxonomy,tests.test_lab_init,tests.test_utils)
      \-Repo (src.instructlab.utils)
      \-exc (src.instructlab.utils)
    gitdb (src.instructlab.utils)
    httpx (src.instructlab.client,src.instructlab.configuration,src.instructlab.utils)
    huggingface_hub 
      \-utils (tests.test_lab_download)
    instructlab 
      \-configuration (src.instructlab.lab,tests.test_config,tests.test_lab_generate,tests.test_lab_init)
      \-lab (src.instructlab.__main__,tests.test_lab,tests.test_lab_diff,tests.test_lab_download,tests.test_lab_generate,tests.test_lab_init,tests.test_lab_train)
      \-model 
      | \-backends 
      |   \-backends (tests.test_backends)
      \-sdg 
      | \-generate_data (tests.test_lab_generate)
      | \-utils (tests.test_lab_generate)
      \-train 
      | \-linux_train (tests.test_lab_train)
      \-training (src.instructlab.configuration)
      \-utils (tests.test_lab,tests.test_utils)
    jsonschema 
      \-protocols (src.instructlab.utils)
      \-validators (src.instructlab.utils)
    langchain_text_splitters (src.instructlab.utils)
    llama_cpp (src.instructlab.sysinfo,tests.test_lab)
    openai (src.instructlab.client)
    pydantic (src.instructlab.configuration)
    pytest (tests.conftest,tests.test_backends,tests.test_config,tests.test_lab,tests.test_lab_diff,tests.test_lab_generate,tests.test_lab_train,tests.test_notebooks,tests.test_utils)
    referencing (src.instructlab.utils)
      \-exceptions (src.instructlab.utils)
      \-jsonschema (src.instructlab.utils)
      \-typing (src.instructlab.utils)
    torch (src.instructlab.sysinfo)
    yaml (src.instructlab.configuration,src.instructlab.utils,tests.test_utils)



3158 lines have been analyzed

Raw metrics
-----------

+----------+-------+------+---------+-----------+
|type      |number |%     |previous |difference |
+==========+=======+======+=========+===========+
|code      |2064   |65.36 |2064     |=          |
+----------+-------+------+---------+-----------+
|docstring |530    |16.78 |530      |=          |
+----------+-------+------+---------+-----------+
|comment   |183    |5.79  |183      |=          |
+----------+-------+------+---------+-----------+
|empty     |381    |12.06 |381      |=          |
+----------+-------+------+---------+-----------+



Duplication
-----------

+-------------------------+------+---------+-----------+
|                         |now   |previous |difference |
+=========================+======+=========+===========+
|nb duplicated lines      |0     |0        |0          |
+-------------------------+------+---------+-----------+
|percent duplicated lines |0.000 |0.000    |=          |
+-------------------------+------+---------+-----------+



Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |0      |0        |0          |
+-----------+-------+---------+-----------+
|refactor   |0      |0        |0          |
+-----------+-------+---------+-----------+
|warning    |0      |0        |0          |
+-----------+-------+---------+-----------+
|error      |0      |0        |0          |
+-----------+-------+---------+-----------+



Messages
--------

+-----------+------------+
|message id |occurrences |
+===========+============+




--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

lint: OK ✔ in 8.12 seconds
pkg: _optional_hooks> python /Users/jkunstle/Developer/github/instructlab/venv/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
pkg: get_requires_for_build_wheel> python /Users/jkunstle/Developer/github/instructlab/venv/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
mypy: packaging backend failed (code=1), with ValueError: invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}

Traceback (most recent call last):
  File "/Users/jkunstle/Developer/github/instructlab/venv/lib/python3.11/site-packages/pyproject_api/_backend.py", line 95, in run
    outcome = backend_proxy(parsed_message["cmd"], **parsed_message["kwargs"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/venv/lib/python3.11/site-packages/pyproject_api/_backend.py", line 36, in __call__
    return getattr(on_object, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/_virtualenv.py", line 22, in parse_config_files
    result = old_parse_config_files(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/dist.py", line 631, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 68, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 129, in read_configuration
    validate(subset, filepath)
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 57, in validate
    raise ValueError(f"{error}\n{summary}") from None
ValueError: invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}

Backend: run command get_requires_for_build_wheel with args {'config_settings': None}
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}

GIVEN VALUE:
    {
        "hpu": {
            "file": [
                "requirements-hpu.txt"
            ]
        },
        "vllm-cuda": {
            "file": [
                "requirements-vllm-cuda.txt"
            ]
        }
    }

OFFENDING RULE: 'propertyNames'

DEFINITION:
    {
        "type": "object",
        "propertyNames": {
            "format": "python-identifier"
        },
        "additionalProperties": false,
        "patternProperties": {
            ".+": {
                "$id": "#/definitions/file-directive",
                "title": "'file:' directive",
                "description": "Value is read from a file (or list of files and then concatenated)",
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "file": {
                        "oneOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        ]
                    }
                },
                "required": [
                    "file"
                ]
            }
        }
    }
Backend: Wrote response {'code': 1, 'exc_type': 'ValueError', 'exc_msg': "invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.\nconfiguration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:\n\n    {format: 'python-identifier'}\n"} to /var/folders/8n/qtnwnvtn3dg3d3xd7z8dsx780000gn/T/pep517_get_requires_for_build_wheel-ma2bjwd9.json
mypy: FAIL ✖ in 0.48 seconds
spellcheck: commands[0]> sh -c 'command -v aspell || (echo "aspell is not installed. Please install it." && exit 1)'
/opt/homebrew/bin/aspell
spellcheck: commands[1]> .tox/spellcheck/bin/python -m pyspelling --config /Users/jkunstle/Developer/github/instructlab/.spellcheck.yml --spellchecker aspell
Spelling check passed :)
spellcheck: OK ✔ in 1.13 seconds
pkg: build_wheel> python /Users/jkunstle/Developer/github/instructlab/venv/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
py3-unit: packaging backend failed (code=1), with ValueError: invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}

Traceback (most recent call last):
  File "/Users/jkunstle/Developer/github/instructlab/venv/lib/python3.11/site-packages/pyproject_api/_backend.py", line 95, in run
    outcome = backend_proxy(parsed_message["cmd"], **parsed_message["kwargs"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/venv/lib/python3.11/site-packages/pyproject_api/_backend.py", line 36, in __call__
    return getattr(on_object, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 410, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
    self.run_setup()
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/_virtualenv.py", line 22, in parse_config_files
    result = old_parse_config_files(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/dist.py", line 631, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 68, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 129, in read_configuration
    validate(subset, filepath)
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 57, in validate
    raise ValueError(f"{error}\n{summary}") from None
ValueError: invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}

Backend: run command build_wheel with args {'wheel_directory': '/Users/jkunstle/Developer/github/instructlab/.tox/pkg/dist', 'config_settings': None, 'metadata_directory': None}
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}

GIVEN VALUE:
    {
        "hpu": {
            "file": [
                "requirements-hpu.txt"
            ]
        },
        "vllm-cuda": {
            "file": [
                "requirements-vllm-cuda.txt"
            ]
        }
    }

OFFENDING RULE: 'propertyNames'

DEFINITION:
    {
        "type": "object",
        "propertyNames": {
            "format": "python-identifier"
        },
        "additionalProperties": false,
        "patternProperties": {
            ".+": {
                "$id": "#/definitions/file-directive",
                "title": "'file:' directive",
                "description": "Value is read from a file (or list of files and then concatenated)",
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "file": {
                        "oneOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        ]
                    }
                },
                "required": [
                    "file"
                ]
            }
        }
    }
Backend: Wrote response {'code': 1, 'exc_type': 'ValueError', 'exc_msg': "invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.\nconfiguration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:\n\n    {format: 'python-identifier'}\n"} to /var/folders/8n/qtnwnvtn3dg3d3xd7z8dsx780000gn/T/pep517_build_wheel-1_wxfm4y.json
py3-unit: FAIL ✖ in 0.25 seconds
pkg: build_wheel> python /Users/jkunstle/Developer/github/instructlab/venv/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
py3-functional: packaging backend failed (code=1), with ValueError: invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}

Traceback (most recent call last):
  File "/Users/jkunstle/Developer/github/instructlab/venv/lib/python3.11/site-packages/pyproject_api/_backend.py", line 95, in run
    outcome = backend_proxy(parsed_message["cmd"], **parsed_message["kwargs"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/venv/lib/python3.11/site-packages/pyproject_api/_backend.py", line 36, in __call__
    return getattr(on_object, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 410, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
    self.run_setup()
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/_virtualenv.py", line 22, in parse_config_files
    result = old_parse_config_files(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/dist.py", line 631, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 68, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 129, in read_configuration
    validate(subset, filepath)
  File "/Users/jkunstle/Developer/github/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 57, in validate
    raise ValueError(f"{error}\n{summary}") from None
ValueError: invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}

Backend: run command build_wheel with args {'wheel_directory': '/Users/jkunstle/Developer/github/instructlab/.tox/pkg/dist', 'config_settings': None, 'metadata_directory': None}
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}

GIVEN VALUE:
    {
        "hpu": {
            "file": [
                "requirements-hpu.txt"
            ]
        },
        "vllm-cuda": {
            "file": [
                "requirements-vllm-cuda.txt"
            ]
        }
    }

OFFENDING RULE: 'propertyNames'

DEFINITION:
    {
        "type": "object",
        "propertyNames": {
            "format": "python-identifier"
        },
        "additionalProperties": false,
        "patternProperties": {
            ".+": {
                "$id": "#/definitions/file-directive",
                "title": "'file:' directive",
                "description": "Value is read from a file (or list of files and then concatenated)",
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "file": {
                        "oneOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        ]
                    }
                },
                "required": [
                    "file"
                ]
            }
        }
    }
Backend: Wrote response {'code': 1, 'exc_type': 'ValueError', 'exc_msg': "invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.\nconfiguration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:\n\n    {format: 'python-identifier'}\n"} to /var/folders/8n/qtnwnvtn3dg3d3xd7z8dsx780000gn/T/pep517_build_wheel-_zxhzkq5.json
py3-functional: FAIL ✖ in 0.26 seconds
tomllint: commands[0]> make toml-lint
  [TOML LINT]  ./...
tomllint: commands[1]> make toml-fmt
  [TOML FMT]   ./...
tomllint: commands[2]> sh -c 'git diff --exit-code || (echo "pyproject.toml formatting is incorrect. Please run \"make toml-fmt\" and commit the changes." && exit 1)'
  ruff: OK (1.04=setup[0.03]+cmd[1.01] seconds)
  lint: OK (8.12=setup[0.01]+cmd[8.11] seconds)
  mypy: FAIL code 1 (0.48 seconds)
  spellcheck: OK (1.13=setup[0.01]+cmd[0.01,1.11] seconds)
  py3-unit: FAIL code 1 (0.25 seconds)
  py3-functional: FAIL code 1 (0.26 seconds)
  tomllint: OK (1.26=setup[0.01]+cmd[0.64,0.59,0.02] seconds)
  evaluation failed :( (12.58 seconds)
```

**Comment by JamesKunstle** [comment]
I tested an end-to-end tox run on a linux machine. Had an initial failure because `expect` and `aspell` weren't installed. Installed those, and everything succeeded except for the py3-functional tests.

**Comment by nathan-weinberg** [comment]
See the linked PR for solution
