### ISSUE TITLE
Every `ilab` invokation or import make a HTTPS call, `ilab` breaks without internet

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#1542]
**Describe the bug**

I noticed that a recent change in InstructLab introduced a very problematic behavior. All import of `instructlab.lab` and therefore all `ilab` calls make a HTTPS connection to Hugging Face Hub. Even `ilab --help` behaves that way. Even worse, it is no longer possible to run `ilab` without an internet connection, unless a previous call has populated a cache.

**To Reproduce**
* install `instructlab` in a virtual environment
* run `XDG_CACHE_HOME=$(pwd)/cache unshare -rn ilab --help`

`XDG_CACHE_HOME=$(pwd)/cache` sets the cache root to a new, empty directory. `unshare -rn` creates a new network namespace without access to the internet.

**Expected behavior**
InstructLab should work without a network connection and not dial home for every call.

**Screenshots**
```
$ XDG_CACHE_HOME=$(pwd)/cache unshare -rn ilab --help
[2024-07-01 07:03:27,681] [WARNING] [real_accelerator.py:162:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2024-07-01 07:03:27,691] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cpu (auto detect)
Traceback (most recent call last):
  File ".tox/py311-unit/bin/ilab", line 5, in <module>
    from instructlab.lab import ilab
  File ".tox/py311-unit/lib/python3.11/site-packages/instructlab/lab.py", line 18, in <module>
    from .model import model as model_group
  File ".tox/py311-unit/lib/python3.11/site-packages/instructlab/model/model.py", line 11, in <module>
    from .evaluate import evaluate
  File ".tox/py311-unit/lib/python3.11/site-packages/instructlab/model/evaluate.py", line 8, in <module>
    from instructlab.eval.mmlu import MMLUBranchEvaluator, MMLUEvaluator
  File ".tox/py311-unit/lib/python3.11/site-packages/instructlab/eval/mmlu.py", line 7, in <module>
    from lm_eval.evaluator import simple_evaluate  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".tox/py311-unit/lib/python3.11/site-packages/lm_eval/__init__.py", line 1, in <module>
    from .evaluator import evaluate, simple_evaluate
  File ".tox/py311-unit/lib/python3.11/site-packages/lm_eval/evaluator.py", line 11, in <module>
    import lm_eval.api.metrics
  File ".tox/py311-unit/lib/python3.11/site-packages/lm_eval/api/metrics.py", line 168, in <module>
    exact_match = hf_evaluate.load("exact_match")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".tox/py311-unit/lib/python3.11/site-packages/evaluate/loading.py", line 748, in load
    evaluation_module = evaluation_module_factory(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".tox/py311-unit/lib/python3.11/site-packages/evaluate/loading.py", line 681, in evaluation_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a module script at exact_match/exact_match.py. Module 'exact_match' doesn't exist on the Hugging Face Hub either.
```

**Device Info (please complete the following information):**
instructlab               0.17.1.dev221
instructlab-eval          0.0.3

**Additional context**

**Comment by tiran** [comment]
See https://github.com/EleutherAI/lm-evaluation-harness/issues/1697

**Comment by nathan-weinberg** [comment]
A new `lm_eval` version is being released later today that should fix this issue: https://github.com/EleutherAI/lm-evaluation-harness/issues/1697#issuecomment-2200185644

cc @danmcp @alinaryan @alimaredia
