### ISSUE TITLE
Default model and backend does match for evaluate

### ISSUE THREAD

**Issue by chudegao** [instructlab/instructlab#1602]
1. By default,  when run evaluate it use  models/merlinite-7b-lab-Q4_K_M.gguf as to be evaluated model. However, it will use vllm as backend which can not serve gguf model.
2. The backend can not be specified in command line, it's an important parameter, it's better can be supported in CLI like '--model'

**To Reproduce**
1. run 'ilab evaluate --benchmark mmlu'
```
(chudg1) [root@llm lab]# ilab evaluate --benchmark mmlu
You are using an aliased command, this will be deprecated in a future release. Please consider using `ilab model evaluate` instead
===================using parameters ========================
benchmark        : mmlu
model            : models/merlinite-7b-lab-Q4_K_M.gguf
base_model       : instructlab/granite-7b-lab
judge_model      : prometheus-eval/prometheus-8x7b-v2.0
output_dir       : eval_data
max_workers      : 40
taxonomy_path    : taxonomy
branch           : None
base_branch      : None
few_shots        : 2
batch_size       : 5
sdg_path         : generated
tls_insecure     : False
tls_client_cert  : 
tls_client_key   : 
tls_client_passwd: 
============================================================
INFO 2024-07-05 09:20:24,177 utils.py:148: _init_num_threads Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO 2024-07-05 09:20:24,177 utils.py:160: _init_num_threads NumExpr defaulting to 8 threads.
INFO 2024-07-05 09:20:24,317 config.py:58: <module> PyTorch version 2.3.0 available.
/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/transformers/configuration_utils.py", line 722, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/transformers/configuration_utils.py", line 825, in _dict_from_json_file
    text = reader.read()
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 176: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/itaas/miniconda3/envs/chudg1/bin/ilab", line 8, in <module>
    sys.exit(ilab())
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/chudg/lab/instructlab/src/instructlab/utils.py", line 551, in wrapper
    return func(*args, **kwargs)
  File "/root/chudg/lab/instructlab/src/instructlab/model/evaluate.py", line 500, in evaluate
    overall_score, individual_scores = evaluator.run()
  File "/root/chudg/lab/eval/src/instructlab/eval/mmlu.py", line 120, in run
    mmlu_output = simple_evaluate(
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/lm_eval/utils.py", line 395, in _wrapper
    return fn(*args, **kwargs)
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/lm_eval/evaluator.py", line 192, in simple_evaluate
    lm = lm_eval.api.registry.get_model(model).create_from_arg_string(
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/lm_eval/api/model.py", line 148, in create_from_arg_string
    return cls(**args, **args2)
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/lm_eval/models/huggingface.py", line 196, in __init__
    self._get_config(
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/lm_eval/models/huggingface.py", line 470, in _get_config
    self._config = transformers.AutoConfig.from_pretrained(
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 965, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/transformers/configuration_utils.py", line 632, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/itaas/miniconda3/envs/chudg1/lib/python3.10/site-packages/transformers/configuration_utils.py", line 726, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'models/merlinite-7b-lab-Q4_K_M.gguf' is not a valid JSON file.
(chudg1) [root@llm lab]# 
```

**Expected behavior**
1. Make sure the default values matched.
3. User can set backend by '--backend' in cli.

**Device Info (please complete the following information):**
```
sys.version: 3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0]
sys.platform: linux
os.name: posix
platform.release: 4.18.0-477.27.1.el8_8.x86_64
platform.machine: x86_64
os-release.ID: rhel
os-release.VERSION_ID: 8.8
os-release.PRETTY_NAME: Red Hat Enterprise Linux 8.8 (Ootpa)
instructlab.version: 0.17.1.dev241
instructlab-dolomite.version: 0.0.1
instructlab-eval.version: 0.0.4
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.2.0
instructlab-sdg.version: 0.0.5.dev30
instructlab-training.version: 0.0.6.dev1
torch.version: 2.3.0+cu121
torch.backends.cpu.capability: AVX512
torch.version.cuda: 12.1
torch.version.hip: None
torch.cuda.available: True
torch.backends.cuda.is_built: True
torch.backends.mps.is_built: False
torch.backends.mps.is_available: False
torch.cuda.bf16: True
torch.cuda.current: 0
torch.cuda.0.name: Tesla V100-PCIE-32GB
torch.cuda.0.free: 31.4
torch.cuda.0.total: 31.7
torch.cuda.0.capability: 7.0
llama_cpp_python.version: 0.2.79
llama_cpp_python.supports_gpu_offload: True
```

**Comment by nathan-weinberg** [comment]
@chudegao please fill out the Device Info

**Comment by chudegao** [comment]
> @chudegao please fill out the Device Info

Updated

**Comment by danmcp** [comment]
@chudegao I think two changes have helped out this issue:

1) should be addressed by: https://github.com/instructlab/instructlab/pull/1692 which uses the backend auto detection if one isn't specified

and for 2) the backend option was added here: https://github.com/instructlab/instructlab/pull/1564/files

Here is an example that evaluates a a gguf model on llama-cpp and the safetensors judge model on llama-cpp (accepting default backend):

```
Generating answers...
WARNING 2024-07-12 22:06:21,226 evaluate.py:276: launch_server When using llama-cpp, we recommend setting max_workers to a maximum of 16
  0%|                                                                                                                                                     | 0/4 [00:00<?, ?it/s]<class 'openai.InternalServerError'> Service Unavailable
<class 'openai.InternalServerError'> Service Unavailable
<class 'openai.InternalServerError'> Service Unavailable
<class 'openai.InternalServerError'> Service Unavailable
<class 'openai.InternalServerError'> Service Unavailable
<class 'openai.InternalServerError'> Service Unavailable
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:38<00:00, 39.63s/it]
Evaluating answers...
INFO 2024-07-12 22:09:40,815 vllm.py:149: run_vllm vLLM starting up on pid 3111 at http://127.0.0.1:54713/v1
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:18<00:00,  2.27s/it]
# SKILL EVALUATION REPORT

## MODEL
models/merlinite-7b-lab-Q4_K_M.gguf

### AVERAGE:
9.0 (across 1)

### TURN ONE:
9.0

### TURN TWO:
N/A

### ERROR RATE:
0.88
```


This does bring up another issue of what should/would happen if you have a backend specified, your model you want to eval is gguf, and your judge model is safetensors.  To enable that we would actually need separate flags for backend and --judge-backend.  If I specify --backend vllm as is, it will hang trying to load the gguf model.

@cdoern
