### ISSUE TITLE
stdout_stderr_to_logger breaks click's error reporting

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#1738]
**Describe the bug**
`stdout_stderr_to_logger` changes `sys.stderr` in a way that is incompatible with click. We should either fix the problem or replace the helper with a different approach.

Also see #1718

**To Reproduce**
```python
>>> import click
>>> import logging
>>> from instructlab.log import stdout_stderr_to_logger

>>> logging.basicConfig()
>>> click.echo("hello")
hello

>>> stdout_stderr_to_logger(logging.getLogger(), None)
>>> click.echo("hello")
ERROR:root:Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/heimes/redhat/ai/instructlab/instructlab/.tox/py311-unit/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
ERROR:root:^^^^^^^^^^^^^^^
ERROR:root:File "/home/heimes/redhat/ai/instructlab/instructlab/.tox/py311-unit/lib/python3.11/site-packages/click/_compat.py", line 99, in __getattr__
    return getattr(self._stream, name)
ERROR:root:^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:root:AttributeError: 'str' object has no attribute 'write'
`

**Comment by leseb** [comment]
Also, I think `stdout_stderr_to_logger` is broken. The log file to serve is not working anymore.
