### ISSUE TITLE
SDG is broken with AssertionError

### ISSUE THREAD

**Issue by bjhargrave** [instructlab/instructlab#1748]
**Describe the bug**

I have updated to the latest HEAD, and now when using data generate, the served model reports an AssertionError. I get the same error on different models.

**To Reproduce**
1. Serve the model
```sh
$ ilab model serve
INFO 2024-07-16 17:11:17,594 instructlab.model.serve:136: Using model '/Users/hargrave/Library/Application Support/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf' with -1 gpu-layers and 4096 max context size.
INFO 2024-07-16 17:11:17,594 instructlab.model.serve:140: Serving model '/Users/hargrave/Library/Application Support/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf' with llama-cpp
INFO 2024-07-16 17:11:27,578 instructlab.model.backends.llama_cpp:242: Replacing chat template:
 {% for message in messages %}
{% if message['role'] == 'user' %}
{{ '<|user|>
' + message['content'] }}
{% elif message['role'] == 'system' %}
{{ '<|system|>
' + message['content'] }}
{% elif message['role'] == 'assistant' %}
{{ '<|assistant|>
' + message['content'] + eos_token }}
{% endif %}
{% if loop.last and add_generation_prompt %}
{{ '<|assistant|>' }}
{% endif %}
{% endfor %}
INFO 2024-07-16 17:11:27,579 instructlab.model.backends.llama_cpp:185: Starting server process, press CTRL+C to shutdown server...
INFO 2024-07-16 17:11:27,579 instructlab.model.backends.llama_cpp:186: After application startup complete see http://127.0.0.1:8000/docs for API.
```
2. ilab data generate
```sh
ilab data generate
INFO 2024-07-16 17:07:40,387 numexpr.utils:161: NumExpr defaulting to 16 threads.
INFO 2024-07-16 17:07:40,497 datasets:58: PyTorch version 2.3.1 available.
INFO 2024-07-16 17:07:40,747 instructlab.model.backends.llama_cpp:99: Trying to connect to model server at http://127.0.0.1:8000/v1
Generating synthetic data using '/Users/hargrave/Library/Application Support/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf' model, taxonomy:'/Users/hargrave/git/instructlab/taxonomy' against http://127.0.0.1:8000/v1 server
INFO 2024-07-16 17:07:40,927 instructlab.sdg:302: Synthesizing new instructions. If you aren't satisfied with the generated instructions, interrupt training (Ctrl-C) and try adjusting your YAML files. Adding more examples may help.
INFO 2024-07-16 17:07:43,718 instructlab.sdg.llmblock:32: LLM server supports batched inputs: False
INFO 2024-07-16 17:07:43,718 instructlab.sdg.pipeline:41: Running block: gen_skill_freeform
INFO 2024-07-16 17:07:43,718 instructlab.sdg.pipeline:42: Dataset({
    features: ['task_description', 'seed_question', 'seed_response'],
    num_rows: 10
})
``` 
5. See error in model serve window
```sh
ERROR 2024-07-16 17:14:09,498 instructlab.model.serve:0: Exception:
ERROR 2024-07-16 17:14:10,481 instructlab.model.serve:0: Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/instructlab/lib/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/instructlab/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/instructlab/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/instructlab/lib/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Expected behavior**

SDG should complete successfully.

**Screenshots**

**Device Info (please complete the following information):**
 - Hardware Specs: M3 Max, 64GB
```sh
$ ilab system info
sys.version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:34:54) [Clang 16.0.6 ]
sys.platform: darwin
os.name: posix
platform.release: 23.5.0
platform.machine: arm64
instructlab.version: 0.17.1.dev494
instructlab-dolomite.version: 0.0.1
instructlab-eval.version: 0.0.9
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.2.0
instructlab-sdg.version: 0.1.2
instructlab-training.version: 0.0.5.1
torch.version: 2.3.1
torch.backends.cpu.capability: NO AVX
torch.version.cuda: None
torch.version.hip: None
torch.cuda.available: False
torch.backends.cuda.is_built: False
torch.backends.mps.is_built: True
torch.backends.mps.is_available: True
llama_cpp_python.version: 0.2.79
llama_cpp_python.supports_gpu_offload: True
```
**Additional context**

**Comment by chrismarth** [comment]
I'm seeing the exact same thing with 0.18.1. Any guidance on how to fix this or work around it so I can do some sort of SDG?

```
$ ilab system info
sys.version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
sys.platform: linux
os.name: posix
platform.release: 5.15.153.1-microsoft-standard-WSL2
platform.machine: x86_64
platform.python_version: 3.11.9
os-release.ID: ubuntu
os-release.VERSION_ID: 22.04
os-release.PRETTY_NAME: Ubuntu 22.04.4 LTS
instructlab.version: 0.18.1
instructlab-dolomite.version: 0.1.1
instructlab-eval.version: 0.1.1
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.4.0
instructlab-sdg.version: 0.2.6
instructlab-training.version: 0.4.2
torch.version: 2.3.1+cu121
torch.backends.cpu.capability: AVX2
torch.version.cuda: 12.1
torch.version.hip: None
torch.cuda.available: True
torch.backends.cuda.is_built: True
torch.backends.mps.is_built: False
torch.backends.mps.is_available: False
torch.cuda.bf16: True
torch.cuda.current.device: 0
torch.cuda.0.name: NVIDIA GeForce RTX 3070
torch.cuda.0.free: 6.9 GB
torch.cuda.0.total: 8.0 GB
torch.cuda.0.capability: 8.6 (see https://developer.nvidia.com/cuda-gpus#compute)
llama_cpp_python.version: 0.2.79
llama_cpp_python.supports_gpu_offload: False
```

**Comment by chrismarth** [comment]
So this appears to be related to the batching check that's done here:

https://github.com/instructlab/sdg/blob/ca30d98bac7922a095bfb661cef1851ffc2df373/src/instructlab/sdg/llmblock.py#L36-L52

```
def server_supports_batched(client, model_id: str) -> bool:
    supported = getattr(client, "server_supports_batched", None)
    if supported is not None:
        return supported
    try:
        # Make a test call to the server to determine whether it supports
        # multiple input prompts per request and also the n parameter
        response = client.completions.create(
            model=model_id, prompt=["test1", "test2"], max_tokens=1, n=3
        )
        # Number outputs should be 2 * 3 = 6
        supported = len(response.choices) == 6
    except openai.InternalServerError:
        supported = False
    client.server_supports_batched = supported
    logger.info(f"LLM server supports batched inputs: {client.server_supports_batched}")
    return supported
```
I'm not familiar enough with this to know where/how to set `server_supports_batched` but if I just override and set `supported` to false this issue goes away.  Any pointers on where to set `server_supports_batched`? I've tried setting `--batch-size=0` on the call to generate but that didn't do anything. Also tried adding to `config.yaml` in various places but nothing worked there either.

**Comment by shivchander** [comment]
llamacpp does not support batched requests. Ideally that `server_supports_batched` function should have returned false and it should have done non-batched generations

cc: @aakankshaduggal @bbrowning @danmcp @markmc

**Comment by bbrowning** [comment]
Before we get this far, there is a check over at https://github.com/instructlab/instructlab/blob/b297f85c356609d1024ff63798d02b8493a56f3a/src/instructlab/data/generate.py#L289-L295 that should avoid this issue when running against the local llama.cpp. In fact, on my local machine, when I do `ilab model serve` followed by `ilab data generate` I don't get this error. Instead, I see:

```
INFO 2024-08-19 17:42:50,294 instructlab.model.backends.llama_cpp:104: Trying to connect to model server at http://127.0.0.1:8000/v1
WARNING 2024-08-19 17:42:50,305 instructlab.data.generate:291: Disabling SDG batching - unsupported with llama.cpp serving
...
```

So, I think the issue is figuring out why the check to see if we're using llama.cpp is failing on some systems?

**Comment by danmcp** [comment]
> So, I think the issue is figuring out why the check to see if we're using llama.cpp is failing on some systems?

I think this is the difference between running serve separate and passing --endpoint-url vs having generate launch lama-cpp.

**Comment by bbrowning** [comment]
> I think this is the difference between running serve separate and passing --endpoint-url vs having generate launch llama-cpp.

I'm not so sure - I tested locally by running serving separately and it correctly detected llama-cpp instead of vllm, although I am on Linux and not a Mac.

@chrismarth Do you have a log snippet like the one @bjhargrave provided from your llama.cpp/ilab model serve terminal? This issue was originally reported on a 0.17.x dev build but you're reporting it on 0.18.1, so I'm curious to see if it's failing in the exact same way or not.

**Comment by bbrowning** [comment]
@danmcp Sorry, I misread your comment - you said passing `--endpoint-url` but I assumed running llama.cpp separately without passing `--endpoint-url` - you may be right there. The exact commands used for `ilab model serve` and `ilab data generate` would be useful to confirm that theory.

**Comment by chrismarth** [comment]
I am running serve separately (I am running in WSL2). Here is my log:

```
$ ilab model serve
INFO 2024-08-19 23:03:33,606 instructlab.model.serve:145: Using model '/home/racerx/.cache/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf' with -1 gpu-layers and 4096 max context size.
INFO 2024-08-19 23:03:33,606 instructlab.model.serve:149: Serving model '/home/racerx/.cache/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf' with llama-cpp
INFO 2024-08-19 23:03:34,115 instructlab.model.backends.llama_cpp:249: Replacing chat template:
 {% for message in messages %}
{% if message['role'] == 'user' %}
{{ '<|user|>
' + message['content'] }}
{% elif message['role'] == 'system' %}
{{ '<|system|>
' + message['content'] }}
{% elif message['role'] == 'assistant' %}
{{ '<|assistant|>
' + message['content'] + eos_token }}
{% endif %}
{% if loop.last and add_generation_prompt %}
{{ '<|assistant|>' }}
{% endif %}
{% endfor %}
INFO 2024-08-19 23:03:34,118 instructlab.model.backends.llama_cpp:192: Starting server process, press CTRL+C to shutdown server...
INFO 2024-08-19 23:03:34,118 instructlab.model.backends.llama_cpp:193: After application startup complete see http://127.0.0.1:8000/docs for API.
ERROR 2024-08-19 23:03:40,569 instructlab.model.serve:0: Exception:
ERROR 2024-08-19 23:03:41,373 instructlab.model.serve:0: Traceback (most recent call last):
  File "/opt/miniconda/envs/instructLab/lib/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/instructLab/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/instructLab/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/instructLab/lib/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception:
ERROR 2024-08-19 23:03:43,113 instructlab.model.serve:0: Traceback (most recent call last):
  File "/opt/miniconda/envs/instructLab/lib/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/instructLab/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/instructLab/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/instructLab/lib/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception:
```

And I am running the gen seperately as follows:

`$ ilab data generate --pipeline full --gpus 1`

**Comment by chrismarth** [comment]
Debugging this a bit more, it does appear that SDG does, in fact, run and complete despite the exceptions logged above.  It just took a lot longer than anticipated (simplifying what I was trying to generate and turning on logging to verify something was actually happening also helped). So, perhaps there is no real issue here - maybe just an unnecessary batch check and potentially confusing log output.

**Comment by bbrowning** [comment]
@chrismarth Thanks for the update! Let's leave this open in case there's something we can do to reduce the confusing log output, as I've run across another user that was tripped up by this.

**Comment by bjhargrave** [comment]
I am wondering if 

https://github.com/abetlen/llama-cpp-python/pull/1796/files#diff-e1c54c405558e9e0e504c401e409eade1e55b9c360436eb8d5d1ccc05b20e2e9

will fix the display of the error.

**Comment by MohamedBengezi** [comment]
Any updates on this? I'm hitting the same issue and it doesn't seem that my ilab recovers or continues after the error. I'm running `ilab model serve` in one window and `ilab data generate` with the `--model` and `--model-family` parameters in a separate window

**Comment by IPvSean** [comment]
I think I am hitting this same error

```
(venv) [ec2-user@ip-172-17-199-246 instructlab]$ ilab data generate
INFO 2024-10-28 19:59:39,402 numexpr.utils:161: NumExpr defaulting to 4 threads.
INFO 2024-10-28 19:59:39,662 datasets:59: PyTorch version 2.3.1 available.
INFO 2024-10-28 19:59:40,462 instructlab.model.backends.llama_cpp:100: Trying to connect to model server at http://0.0.0.0:8000/v1
WARNING 2024-10-28 19:59:44,003 instructlab.data.generate:270: Disabling SDG batching - unsupported with llama.cpp serving
Generating synthetic data using 'full' pipeline, '/home/ec2-user/.cache/instructlab/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf' model, '/home/ec2-user/.local/share/instructlab/taxonomy' taxonomy, against http://0.0.0.0:48105/v1 server
INFO 2024-10-28 19:59:44,241 instructlab.sdg.generate_data:356: Synthesizing new instructions. If you aren't satisfied with the generated instructions, interrupt training (Ctrl-C) and try adjusting your YAML files. Adding more examples may help.
INFO 2024-10-28 19:59:44,251 instructlab.sdg.pipeline:153: Running pipeline single-threaded
INFO 2024-10-28 19:59:44,252 instructlab.sdg.pipeline:197: Running block: duplicate_document_col
INFO 2024-10-28 19:59:44,252 instructlab.sdg.pipeline:198: Dataset({
    features: ['icl_document', 'document', 'document_outline', 'domain', 'icl_query_1', 'icl_query_2', 'icl_query_3', 'icl_response_1', 'icl_response_2', 'icl_response_3'],
    num_rows: 20
})
Exception:
Traceback (most recent call last):
  File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 301, in app
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception:
Traceback (most recent call last):
  File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception:
Traceback (most recent call last):
  File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
INFO 2024-10-28 19:59:45,576 instructlab.sdg.llmblock:51: LLM server supports batched inputs: False
INFO 2024-10-28 19:59:45,576 instructlab.sdg.pipeline:197: Running block: gen_spellcheck
INFO 2024-10-28 19:59:45,577 instructlab.sdg.pipeline:198: Dataset({
    features: ['icl_document', 'document', 'document_outline', 'domain', 'icl_query_1', 'icl_query_2', 'icl_query_3', 'icl_response_1', 'icl_response_2', 'icl_response_3', 'base_document'],
    num_rows: 20
})
/home/ec2-user/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/llama.py:1054: RuntimeWarning: Detected duplicate leading "<s>" in prompt, this will likely reduce response quality, consider removing it...
  warnings.warn(

^C

ç^C
Aborted!
```

**Comment by apcameron** [comment]
Is there any known workaround for this error?
What was the last version that is know to work correctly?

**Comment by bbrowning** [comment]
The immediate workaround for this error is to use the vllm backend (`ilab model serve --backend vllm`) but that's only an option for Linux machines. I've personally experienced this error but my data generation still completed, and there's at least one more user report of data generation finishing despite the error. However, I'm also working on a fix to better identify llama-cpp-python at least in the most common cases so we can hopefully avoid it giving the big assertion errors at all. I hope to have that fix merged within a couple days to the instructlab/sdg repository, and then we'll see how quickly we can get it in a release of SDG and then a version bump in this repo to pull in the fixed version.

**Comment by bbrowning** [comment]
This issue should be fixed now, at least in most cases. Can any of the users that reported this issue let me know if you're not seeing this fixed in InstructLab 0.22 or newer?
