### ISSUE TITLE
Build of rocm container fails

### ISSUE THREAD

**Issue by dtobolik** [instructlab/instructlab#1752]
The rocm container doesn't build. Applied fixes break `ilab model serve` which ends in core dump

**Steps to reproduce**
```bash
git clone https://github.com/instructlab/instructlab.git
cd instructlab
make rocm-gfx90a
```

**Expected behaviour**
Container builds

**Actual behaviour**
```
...
      -- Found Threads: TRUE
      -- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
      -- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
      -- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
      CMake Warning at vendor/llama.cpp/CMakeLists.txt:312 (message):
        OpenMP not found
      
      
      -- The HIP compiler identification is Clang 17.0.6
      CMake Error at /usr/share/cmake/Modules/CMakeDetermineHIPCompiler.cmake:217 (message):
        The ROCm root directory:
      
         /usr/local
      
        does not contain the HIP runtime CMake package, expected at one of:
      
         /usr/local/lib/cmake/hip-lang/hip-lang-config.cmake
         /usr/local/lib64/cmake/hip-lang/hip-lang-config.cmake
         /usr/local/lib/x86_64-redhat-linux-gnu/cmake/hip-lang/hip-lang-config.cmake
      
      Call Stack (most recent call first):
        vendor/llama.cpp/CMakeLists.txt:591 (enable_language)
      
      
      -- Configuring incomplete, errors occurred!
      
      *** CMake configuration failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (llama-cpp-python)
Error: building at STEP "RUN --mount=type=cache,sharing=locked,id=pipcache,target=${PIP_CACHE_DIR},mode=777,z pip cache remove llama_cpp_python &&     umask 0000 &&     CMAKE_ARGS="-DLLAMA_HIPBLAS=on -DCMAKE_C_COMPILER=/usr/bin/clang-${CLANG_VER} -DCMAKE_CXX_COMPILER=/usr/bin/clang++-${CLANG_VER} -DAMDGPU_TARGETS=${AMDGPU_ARCH}"     FORCE_CMAKE=1     ${VIRTUAL_ENV}/bin/pip install -c ${VIRTUAL_ENV}/constraints.txt llama-cpp-python": while running runtime: exit status 1
make: *** [Makefile:114: rocm-gfx90a] Error 1
```

**Device Info:**
 - Hardware Specs: AMD Instinct MI210 (gfx-90a)
 - OS Version: Fedora 40
 - Python Version: 3.11.9
 - Podman Version: 5.0.2
 - Toolbox version: 0.0.99.5
 - Target: rocm-gfx90a
 - ROCm Version: 6.0.2

# Fixing the issue
From the output of CMake there are 2 issues:
- OpenMP is missing
- ROCm root dir is incorrect

I added these lines to the `containers/rocm/Containerfile`
```diff
diff --git a/containers/rocm/Containerfile b/containers/rocm/Containerfile
index bb2bdbf..8df38bc 100644
--- a/containers/rocm/Containerfile
+++ b/containers/rocm/Containerfile
@@ -21,7 +21,7 @@ ENV AMDGPU_ARCH="${AMDGPU_ARCH}" \
 COPY containers/rocm/remove-gfx.sh /tmp/
 RUN --mount=type=cache,target=/var/cache/dnf,z \
     dnf install -y --nodocs --setopt=install_weak_deps=False --setopt=keepcache=True \
-    rocm-runtime hipblas hiprand hipsparse lld-libs ${PYTHON} ${PYTHON}-devel nvtop radeontop make git gh && \
+    rocm-runtime hipblas hiprand hipsparse lld-libs libomp${CLANG_VER}-devel ${PYTHON} ${PYTHON}-devel nvtop radeontop make git gh && \
     /tmp/remove-gfx.sh
 # virtual env, umask 0000 to allow end-user to write to venv later
 ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \
@@ -65,7 +65,7 @@ FROM pytorch AS llama
 RUN --mount=type=cache,sharing=locked,id=pipcache,target=${PIP_CACHE_DIR},mode=777,z \
     pip cache remove llama_cpp_python && \
     umask 0000 && \
-    CMAKE_ARGS="-DLLAMA_HIPBLAS=on -DCMAKE_C_COMPILER=/usr/bin/clang-${CLANG_VER} -DCMAKE_CXX_COMPILER=/usr/bin/clang++-${CLANG_VER} -DAMDGPU_TARGETS=${AMDGPU_ARCH}" \
+    CMAKE_ARGS="-DLLAMA_HIPBLAS=on -DCMAKE_C_COMPILER=/usr/bin/clang-${CLANG_VER} -DCMAKE_CXX_COMPILER=/usr/bin/clang++-${CLANG_VER} -DAMDGPU_TARGETS=${AMDGPU_ARCH} -DCMAKE_HIP_COMPILER_ROCM_ROOT=/usr \
     FORCE_CMAKE=1 \
     ${VIRTUAL_ENV}/bin/pip install -c ${VIRTUAL_ENV}/constraints.txt llama-cpp-python
```

However the build still fails, which I found is known issue in `llama-cpp-python` described here https://github.com/abetlen/llama-cpp-python/issues/1481
Output from the failed build:
```
...
      -- HIP and hipBLAS found
      -- Warning: ccache not found - consider installing it for faster compilation or disable this warning with LLAMA_CCACHE=OFF
      -- CMAKE_SYSTEM_PROCESSOR: x86_64
      -- x86 detected
      CMake Warning (dev) at CMakeLists.txt:26 (install):
        Target llama has PUBLIC_HEADER files but no PUBLIC_HEADER DESTINATION.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      CMake Warning (dev) at CMakeLists.txt:35 (install):
        Target llama has PUBLIC_HEADER files but no PUBLIC_HEADER DESTINATION.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Configuring done (2.6s)
      CMake Error in vendor/llama.cpp/examples/llava/CMakeLists.txt:
        HIP_ARCHITECTURES is empty for target "llava_shared".
      
      
      -- Generating done (0.0s)
      CMake Generate step failed.  Build files cannot be regenerated correctly.
      
      *** CMake configuration failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (llama-cpp-python)
Error: building at STEP "RUN --mount=type=cache,sharing=locked,id=pipcache,target=${PIP_CACHE_DIR},mode=777,z pip cache remove llama_cpp_python &&     umask 0000 &&     CMAKE_ARGS="-DLLAMA_HIPBLAS=on -DCMAKE_C_COMPILER=/usr/bin/clang-${CLANG_VER} -DCMAKE_CXX_COMPILER=/usr/bin/clang++-${CLANG_VER} -DAMDGPU_TARGETS=${AMDGPU_ARCH} -DCMAKE_HIP_COMPILER_ROCM_ROOT=/usr"     FORCE_CMAKE=1     ${VIRTUAL_ENV}/bin/pip install -c ${VIRTUAL_ENV}/constraints.txt llama-cpp-python": while running runtime: exit status 1
make: *** [Makefile:114: rocm-gfx90a] Error 1
```
So as suggested I turned llava build off by adding `-DLLAVA_BUILD=OFF`
```diff
diff --git a/containers/rocm/Containerfile b/containers/rocm/Containerfile
index bb2bdbf..93296c0 100644
--- a/containers/rocm/Containerfile
+++ b/containers/rocm/Containerfile
@@ -21,7 +21,7 @@ ENV AMDGPU_ARCH="${AMDGPU_ARCH}" \
 COPY containers/rocm/remove-gfx.sh /tmp/
 RUN --mount=type=cache,target=/var/cache/dnf,z \
     dnf install -y --nodocs --setopt=install_weak_deps=False --setopt=keepcache=True \
-    rocm-runtime hipblas hiprand hipsparse lld-libs ${PYTHON} ${PYTHON}-devel nvtop radeontop make git gh && \
+    rocm-runtime hipblas hiprand hipsparse lld-libs libomp${CLANG_VER}-devel ${PYTHON} ${PYTHON}-devel nvtop radeontop make git gh && \
     /tmp/remove-gfx.sh
 # virtual env, umask 0000 to allow end-user to write to venv later
 ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \
@@ -65,7 +65,7 @@ FROM pytorch AS llama
 RUN --mount=type=cache,sharing=locked,id=pipcache,target=${PIP_CACHE_DIR},mode=777,z \
     pip cache remove llama_cpp_python && \
     umask 0000 && \
-    CMAKE_ARGS="-DLLAMA_HIPBLAS=on -DCMAKE_C_COMPILER=/usr/bin/clang-${CLANG_VER} -DCMAKE_CXX_COMPILER=/usr/bin/clang++-${CLANG_VER} -DAMDGPU_TARGETS=${AMDGPU_ARCH}" \
+    CMAKE_ARGS="-DLLAMA_HIPBLAS=on -DCMAKE_C_COMPILER=/usr/bin/clang-${CLANG_VER} -DCMAKE_CXX_COMPILER=/usr/bin/clang++-${CLANG_VER} -DAMDGPU_TARGETS=${AMDGPU_ARCH} -DCMAKE_HIP_COMPILER_ROCM_ROOT=/usr -DLLAVA_BUILD=OFF" \
     FORCE_CMAKE=1 \
     ${VIRTUAL_ENV}/bin/pip install -c ${VIRTUAL_ENV}/constraints.txt llama-cpp-python
```
## Build issues
After these changes the container **builds successfully**, however there is issue with `ilab model serve`

There is also issue with permissions on `/opt/app-root/.cache/instructlab` after running `ilab config init`
```
$ ilab config init
Traceback (most recent call last):
  File "/opt/app-root/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/instructlab/lab.py", line 101, in ilab
    cfg.init(ctx, config_file, debug_level)
  File "/opt/app-root/lib64/python3.11/site-packages/instructlab/configuration.py", line 598, in init
    ensure_storage_directories_exist()
  File "/opt/app-root/lib64/python3.11/site-packages/instructlab/configuration.py", line 546, in ensure_storage_directories_exist
    os.makedirs(dirpath, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/opt/app-root/.cache/instructlab'
```

**Steps to reproduce**
 - modify the Containerfile as described
```bash
make rocm-gfx90a
make toolbox-rocm
toolbox exter instructlab
sudo chown -R $(whoami) /opt/app-root/.cache # fix the permission denied issue
ilab config init
ilab model download
ilab model serve
```

**Result**
Commands that work as expected:
 - `ilab`
 - `ilab config init`
 - `ilab model download`
 - `ilab taxonomy diff`

Commands with issues:
```
$ ilab model serve
INFO 2024-07-17 05:02:55,769 instructlab.model.serve:136: Using model '/home/dtobolik/.local/share/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf' with -1 gpu-layers and 4096 max context size.
INFO 2024-07-17 05:02:55,769 instructlab.model.serve:140: Serving model '/home/dtobolik/.local/share/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf' with llama-cpp
Aborted (core dumped)
```
And potentially `ilab model chat` and `ilab data generate` as they depend on the server running

**Additional information from `ilab system info`**
```
sys.version: 3.11.9 (main, Apr 17 2024, 00:00:00) [GCC 14.0.1 20240411 (Red Hat 14.0.1-0)]
sys.platform: linux
os.name: posix
platform.release: 6.8.9-300.fc40.x86_64
platform.machine: x86_64
os-release.ID: fedora
os-release.VERSION_ID: 40
os-release.PRETTY_NAME: Fedora Linux 40 (Toolbx Container Image)
instructlab.version: 0.17.1.dev495
instructlab-dolomite.version: 0.1.0
instructlab-eval.version: 0.1.0
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.2.0
instructlab-sdg.version: 0.1.2
instructlab-training.version: 0.2.0
torch.version: 2.3.1+rocm5.7
torch.backends.cpu.capability: AVX512
torch.version.cuda: None
torch.version.hip: 5.7.31921-d1770ee1b
torch.cuda.available: True
torch.backends.cuda.is_built: True
torch.backends.mps.is_built: False
torch.backends.mps.is_available: False
torch.cuda.bf16: True
torch.cuda.current: 0
torch.cuda.0.name: AMD Instinct MI210
torch.cuda.0.free: 42.4
torch.cuda.0.total: 64.0
torch.cuda.0.capability: 9.0
llama_cpp_python.version: 0.2.79
llama_cpp_python.supports_gpu_offload: True
```

**Comment by tiran** [comment]
I'm the original author of the ROCm container. This is some nice work and a very thorough analysis of problems. Very impressive!

- I have noticed problems with ROCm container before, but haven't had any time to work on the problem. #855 is a related issue.
- it might be a good idea to look into F41 and ROCM 6.1. I have seen reports that ROCm 6.0 has performance issues on professional AMD Instinct cards.
- Until very recently, InstructLab was using the current working directory to store files. This has changed in #1471. The container file resets `$HOME`. For toolbx and the new storage system, it would be better to keep `$HOME`.

Could you please open a PR with your proposed changes? It makes it easier to discuss individual changes.

**Comment by dtobolik** [comment]
Backtrace from gdb
```
#0  0x00007ffff798f4a4 in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff7936c4e in raise () from /lib64/libc.so.6
#2  0x00007ffff791e902 in abort () from /lib64/libc.so.6
#3  0x00007fffe54d9bfb in rocblas_abort_once() [clone .llvm.17766239630633246025] () from /lib64/librocblas.so.4
#4  0x00007fffe54d9b62 in rocblas_abort () from /lib64/librocblas.so.4
#5  0x00007fffe52f3d7a in (anonymous namespace)::get_library_and_adapter(std::shared_ptr<Tensile::MasterSolutionLibrary<Tensile::ContractionProblem, Tensile::ContractionSolution> >*, std::shared_ptr<hipDeviceProp_tR0600>*, int) () from /lib64/librocblas.so.4
#6  0x00007fffe5d28b76 in ?? () from /opt/app-root/lib64/python3.11/site-packages/llama_cpp/libllama.so
#7  0x00007fffe5d291b9 in ggml_backend_cuda_get_device_count () from /opt/app-root/lib64/python3.11/site-packages/llama_cpp/libllama.so
#8  0x00007fffe5dbf654 in ?? () from /opt/app-root/lib64/python3.11/site-packages/llama_cpp/libllama.so
#9  0x00007fffe5db970b in llama_load_model_from_file () from /opt/app-root/lib64/python3.11/site-packages/llama_cpp/libllama.so
#10 0x00007fffe6af4056 in ffi_call_unix64 () from /lib64/libffi.so.8
#11 0x00007fffe6af06a0 in ffi_call_int.lto_priv () from /lib64/libffi.so.8
#12 0x00007fffe6af34ee in ffi_call () from /lib64/libffi.so.8
```
It might be some incompatibility between llama and rocblas, but I didn't find any related issue in llama-cpp-python or llama.cpp
