### ISSUE TITLE
e2e test runner hardcodes the data path

### ISSUE THREAD

**Issue by RobotSail** [instructlab/instructlab#1771]
In our e2e tests, we currently use a temporary directory for all of the data we store and read from. But the current e2e test runner uses a train profile which has the data path hard-coded. This leads to errors such as the following:

[e2e workflow](https://github.com/instructlab/instructlab/actions/runs/9981882717/job/27586545608#step:13:321)

```
Train the model - Wed Jul 17 09:58:32 PM UTC 2024
INFO 2024-07-17 21:58:33,905 numexpr.utils:161: NumExpr defaulting to 8 threads.
INFO 2024-07-17 21:58:34,027 datasets:58: PyTorch version 2.3.1 available.
[2024-07-17 21:58:38,622] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/actions-runner/_work/instructlab/instructlab/venv/bin/ilab", line 8, in <module>
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
    sys.exit(ilab())
             ^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.1), only 1.0.0 is known to be compatible
LINUX_TRAIN.PY: NUM EPOCHS IS:  1
LINUX_TRAIN.PY: TRAIN FILE IS:  taxonomy_data/train_gen.jsonl
LINUX_TRAIN.PY: TEST FILE IS:  taxonomy_data/test_gen.jsonl
LINUX_TRAIN.PY: Using device 'cuda:0'
  NVidia CUDA version: 12.1
  AMD ROCm HIP version: n/a
  cuda:0 is 'NVIDIA A10G' (21.8 GiB of 22.1 GiB free, capability: 8.6)
LINUX_TRAIN.PY: LOADING DATASETS
         ^^^^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/instructlab/clickext.py", line 196, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/instructlab/model/train.py", line 450, in train
    training_results_dir = linux_train(
                           ^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/instructlab/train/linux_train.py", line 220, in linux_train
    train_dataset = load_dataset(
                    ^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/datasets/load.py", line 2594, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/datasets/load.py", line 2266, in load_dataset_builder
    dataset_module = dataset_module_factory(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/datasets/load.py", line 1805, in dataset_module_factory
    ).get_module()
      ^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/datasets/load.py", line 1142, in get_module
    data_files = DataFilesDict.from_patterns(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/datasets/data_files.py", line 721, in from_patterns
    else DataFilesList.from_patterns(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/datasets/data_files.py", line 624, in from_patterns
    resolve_pattern(
  File "/actions-runner/_work/instructlab/instructlab/venv/lib64/python3.11/site-packages/datasets/data_files.py", line 411, in resolve_pattern
    raise FileNotFoundError(error_msg)
FileNotFoundError: Unable to find '/actions-runner/_work/instructlab/instructlab/taxonomy_data/train_gen.jsonl'
```

**Comment by nathan-weinberg** [comment]
@RobotSail can i assign this to you?

**Comment by RobotSail** [comment]
@nathan-weinberg Yes

**Comment by nathan-weinberg** [comment]
@RobotSail just checking in to see if this is still relevant

**Comment by alimaredia** [comment]
Closed by https://github.com/instructlab/instructlab/pull/2291
