### ISSUE TITLE
--max-ctx-size does not take effect when serve model with vllm

### ISSUE THREAD

**Issue by chudegao** [instructlab/instructlab#1773]
When specify --max-ctx-size in 'ilab serve --backend vllm ' command,  vllm still use default max seq length 32768 which may cause OOM.

```
(dlipy3) [root@lab instructlab]# ilab serve --model-path /root/train3 --backend vllm --max-ctx-size 2048
You are using an aliased command, this will be deprecated in a future release. Please consider using `ilab model serve` instead
Parameters:
     model_path: PosixPath('/root/train3') 	[type: pathlib.PosixPath, src: commandline]
        backend: 'vllm'   	[type: str, src: commandline]
   max_ctx_size: 2048     	[type: int, src: commandline]
     gpu_layers: -1       	[type: int, src: default]
    num_threads: None     	[type: None, src: default]
   model_family: None     	[type: None, src: default]
       log_file: None     	[type: None, src: default]
  chat_template: None     	[type: None, src: default]
DEBUG 2024-07-18 02:11:03,548 instructlab.model.backends.backends:198: Auto-detecting backend for model /root/train3
DEBUG 2024-07-18 02:11:03,548 instructlab.model.backends.backends:161: Model is a directory and system is Linux, using vllm backend.
DEBUG 2024-07-18 02:11:03,548 instructlab.model.backends.backends:206: Auto-detected backend: vllm
DEBUG 2024-07-18 02:11:03,548 instructlab.model.backends.backends:217: Validating 'vllm' backend
INFO 2024-07-18 02:11:03,548 instructlab.model.serve:136: Using model '/root/train3' with -1 gpu-layers and 2048 max context size.
INFO 2024-07-18 02:11:03,548 instructlab.model.serve:140: Serving model '/root/train3' with vllm
DEBUG 2024-07-18 02:11:03,549 instructlab.model.backends.vllm:184: vLLM serving command is: ['/opt/anaconda3/envs/dlipy3/bin/python', '-m', 'vllm.entrypoints.openai.api_server', '--model', '/root/train3', '--chat-template', '/tmp/tmp197so27u', '--distributed-executor-backend', 'mp', '--host', '10.244.128.61', '--port', '8003']
INFO 2024-07-18 02:11:03,549 instructlab.model.backends.vllm:196: vLLM starting up on pid 86818 at http://10.244.128.61:8003/v1
INFO 07-18 02:11:06 api_server.py:177] vLLM API server version 0.5.0.post1
INFO 07-18 02:11:06 api_server.py:178] args: Namespace(host='10.244.128.61', port=8003, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, chat_template='/tmp/tmp197so27u', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/root/train3', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend='mp', worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, image_processor=None, image_processor_revision=None, disable_image_processor=False, scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, model_loader_extra_config=None, preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
INFO 07-18 02:11:06 llm_engine.py:164] Initializing an LLM engine (v0.5.0.post1) with config: model='/root/train3', speculative_config=None, tokenizer='/root/train3', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/root/train3)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 07-18 02:11:06 selector.py:161] Cannot use FlashAttention-2 backend due to sliding window.
INFO 07-18 02:11:06 selector.py:52] Using XFormers backend.
[rank0]:[W ProcessGroupGloo.cpp:721] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
INFO 07-18 02:11:07 selector.py:161] Cannot use FlashAttention-2 backend due to sliding window.
INFO 07-18 02:11:07 selector.py:52] Using XFormers backend.
[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 196, in <module>
[rank0]:     engine = AsyncLLMEngine.from_engine_args(
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 415, in from_engine_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 355, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 490, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 230, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:                           ^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/executor/multiproc_gpu_executor.py", line 145, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/executor/distributed_gpu_executor.py", line 25, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 41, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/executor/multiproc_gpu_executor.py", line 69, in _init_executor
[rank0]:     self._run_workers("load_model",
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/executor/multiproc_gpu_executor.py", line 122, in _run_workers
[rank0]:     driver_worker_output = driver_worker_method(*args, **kwargs)
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/worker/worker.py", line 131, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 152, in load_model
[rank0]:     self.model = get_model(
[rank0]:                  ^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py", line 21, in get_model
[rank0]:     return loader.load_model(model_config=model_config,
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 261, in load_model
[rank0]:     model = _initialize_model(model_config, self.load_config,
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 98, in _initialize_model
[rank0]:     return model_class(config=model_config.hf_config,
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 340, in __init__
[rank0]:     self.model = LlamaModel(config,
[rank0]:                  ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 262, in __init__
[rank0]:     self.layers = nn.ModuleList([
[rank0]:                                 ^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 263, in <listcomp>
[rank0]:     LlamaDecoderLayer(config=config,
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 200, in __init__
[rank0]:     self.mlp = LlamaMLP(
[rank0]:                ^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 69, in __init__
[rank0]:     self.down_proj = RowParallelLinear(input_size=intermediate_size,
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/model_executor/layers/linear.py", line 731, in __init__
[rank0]:     self.quant_method.create_weights(
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/vllm/model_executor/layers/linear.py", line 94, in create_weights
[rank0]:     weight = Parameter(torch.empty(sum(output_partition_sizes),
[rank0]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/dlipy3/lib/python3.11/site-packages/torch/utils/_device.py", line 78, in __torch_function__
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 
^CINFO 2024-07-18 02:11:11,723 instructlab.model.backends.vllm:71: vLLM server terminated by keyboard
DEBUG 2024-07-18 02:11:11,723 instructlab.model.backends.backends:243: Sending SIGINT to vLLM server PID 86818
DEBUG 2024-07-18 02:11:11,724 instructlab.model.backends.backends:246: Waiting for vLLM server to shut down gracefully
DEBUG 2024-07-18 02:11:11,724 instructlab.model.backends.backends:243: Sending SIGINT to vLLM server PID 86818
DEBUG 2024-07-18 02:11:11,724 instructlab.model.backends.backends:246: Waiting for vLLM server to shut down gracefully
```

**To Reproduce**
Run 'ilab serve --backend vllm --max-ctx-size 2048 --model-path <model path>'

**Expected behavior**
vllm use specified max seq len 

**Screenshots**

**Device Info (please complete the following information):**
(ilab) [root@dlcgpu lab]# ilab sysinfo
instructlab.version: 0.17.1.dev494
sys.version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
sys.platform: linux
os.name: posix
platform.release: 4.18.0-477.27.1.el8_8.x86_64
platform.machine: x86_64
os-release.ID: rhel
os-release.VERSION_ID: 9.4
os-release.PRETTY_NAME: Red Hat Enterprise Linux 9.4
torch.version: 2.3.1+cu121
torch.backends.cpu.capability: AVX512
torch.version.cuda: 12.1
torch.version.hip: None
torch.cuda.available: True
torch.backends.cuda.is_built: True
torch.backends.mps.is_built: False
torch.backends.mps.is_available: False
torch.cuda.bf16: True
torch.cuda.current: 0
torch.cuda.0.name: NVIDIA L4
torch.cuda.0.free: 3.7
torch.cuda.0.total: 22.0
torch.cuda.0.capability: 8.9
llama_cpp_python.version: 0.2.75
llama_cpp_python.supports_gpu_offload: True

**Additional context**

**Comment by leseb** [comment]
This is unfortunately expected, when passing `--backend vllm` or when it is autodetected you need to pass vllm args like so:

```
ilab model serve --backend vllm -- --max-model-len=2048
```

Please refer to the list of args here: https://docs.vllm.ai/en/stable/serving/openai_compatible_server.html#command-line-arguments-for-the-server

Thanks.

I'll send a PR to clarify that.
