### ISSUE TITLE
Can't get up running the IBM Granite Code Model

### ISSUE THREAD

**Issue by jovst** [instructlab/instructlab#1817]
Hi, I heard about this tool at the Wearedevelopers conference and wanted to try it out.

I tried to use the IBM Granite Code Instruct Model on Huggingface

https://huggingface.co/ibm-granite/granite-8b-code-instruct-GGUF

**I downloaded it with this command:**

`HF_TOKEN=***** ilab model download --repository=ibm-granite/granite-8b-code-instruct-GGUF --filename=granite-8b-code-instruct.Q4_K_M.gguf`

**When I try to start it with:**

`ilab model serve --model-path models/granite-8b-code-instruct.Q4_K_M.gguf`

**I get the following error:**

```
Traceback (most recent call last):
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/instructlab/model/serve.py", line 58, in serve
    server(
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/instructlab/server.py", line 190, in server
    raise ServerException(f "failed creating the server application: {exc}") from exc
instructlab.server.ServerException: failed creating the server application: Failed to load model from file: models/granite-8b-code-instruct.Q4_K_M.gguf
```

What am I doing wrong, or am I missing something?
I am relatively new to the topic and have followed all the steps in the Github README to install ilab

**This is the output of ilab sysinfo:**

```
instructlab.version: 0.17.1
sys.version: 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
sys.platform: linux
os.name: posix
platform.release: 6.5.0-44-generic
platform.machine: x86_64
os-release.ID: ubuntu
os-release.VERSION_ID: 22.04
os-release.PRETTY_NAME: Ubuntu 22.04.4 LTS
torch.version: 2.3.1+cpu
torch.backends.cpu.capability: AVX2
torch.version.cuda: None
torch.version.hip: None
torch.cuda.available: False
torch.backends.cuda.is_built: False
torch.backends.mps.is_built: False
torch.backends.mps.is_available: False
llama_cpp_python.version: 0.2.75
llama_cpp_python.supports_gpu_offload: False
```

**Comment by nathan-weinberg** [comment]
@jovst is this the same problem as https://github.com/instructlab/instructlab/issues/1338?

**Comment by jovst** [comment]
> @jovst is this the same problem as #1338?

Unfortunately not, no matter how I execute the command, whether with ./ or without, the same error message remains:

**Here again in total:**

`(venv) root@user:/home/user/instructlab# ilab model serve --model-path ./models/granite-8b-code-instruct.Q4_K_M.gguf
INFO 2024-07-22 20:35:27,174 serve.py:51: serve Using model './models/granite-8b-code-instruct.Q4_K_M.gguf' with -1 gpu-layers and 4096 max context size.
ERROR 2024-07-22 20:35:27,523 llama_cpp:0: flush Traceback (most recent call last):
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/instructlab/server.py", line 177, in server
    app = create_app(settings=settings)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/llama_cpp/server/app.py", line 147, in create_app
    set_llama_proxy(model_settings=model_settings)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/llama_cpp/server/app.py", line 68, in set_llama_proxy
    _llama_proxy = LlamaProxy(models=model_settings)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/llama_cpp/server/model.py", line 31, in __init__
    self._current_model = self.load_llama_from_model_settings(
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/llama_cpp/server/model.py", line 217, in load_llama_from_model_settings
    _model = create_fn(
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/llama_cpp/llama.py", line 338, in __init__
    self._model = _LlamaModel(
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/llama_cpp/_internals.py", line 57, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: ./models/granite-8b-code-instruct.Q4_K_M.gguf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/instructlab/model/serve.py", line 58, in serve
    server(
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/instructlab/server.py", line 190, in server
    raise ServerException(f"failed creating the server application: {exc}") from exc
instructlab.server.ServerException: failed creating the server application: Failed to load model from file: ./models/granite-8b-code-instruct.Q4_K_M.gguf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/instructlab/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/instructlab/model/serve.py", line 69, in serve
    click.secho(f"Error creating server: {exc}", fg="red")
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/termui.py", line 634, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/_compat.py", line 99, in __getattr__
    return getattr(self._stream, name)
AttributeError: 'str' object has no attribute 'write'
`

**if the path does not match, I get a different error message:**

`(venv) root@user:/home/user/instructlab# ilab model serve --model-path ./models/granite-8b-code-instruct.Q4_K_M.ggufff
INFO 2024-07-22 20:44:09,666 serve.py:51: serve Using model './models/granite-8b-code-instruct.Q4_K_M.ggufff' with -1 gpu-layers and 4096 max context size.
ERROR 2024-07-22 20:44:09,718 llama_cpp:0: flush Traceback (most recent call last):
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/instructlab/server.py", line 177, in server
    app = create_app(settings=settings)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/llama_cpp/server/app.py", line 147, in create_app
    set_llama_proxy(model_settings=model_settings)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/llama_cpp/server/app.py", line 68, in set_llama_proxy
    _llama_proxy = LlamaProxy(models=model_settings)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/llama_cpp/server/model.py", line 31, in __init__
    self._current_model = self.load_llama_from_model_settings(
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/llama_cpp/server/model.py", line 217, in load_llama_from_model_settings
    _model = create_fn(
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/llama_cpp/llama.py", line 336, in __init__
    raise ValueError(f"Model path does not exist: {model_path}")
ValueError: Model path does not exist: ./models/granite-8b-code-instruct.Q4_K_M.ggufff

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/instructlab/model/serve.py", line 58, in serve
    server(
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/instructlab/server.py", line 190, in server
    raise ServerException(f"failed creating the server application: {exc}") from exc
instructlab.server.ServerException: failed creating the server application: Model path does not exist: ./models/granite-8b-code-instruct.Q4_K_M.ggufff

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/instructlab/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/instructlab/model/serve.py", line 69, in serve
    click.secho(f"Error creating server: {exc}", fg="red")
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/termui.py", line 634, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
  File "/home/user/instructlab/venv/lib/python3.10/site-packages/click/_compat.py", line 99, in __getattr__
    return getattr(self._stream, name)
AttributeError: 'str' object has no attribute 'write'
`

i don't understand it, the default model downloaded with the normal download command works, but none of the gguf files i downloaded from huggingface

**Comment by bjhargrave** [comment]
I think you need to update llama_cpp_python to 0.2.79

https://github.com/instructlab/instructlab/blob/c6adcb5ddd84d9358a2db56c5f30b237420f9b13/requirements.txt#L15

This is newer than the version in 0.2.75.

**Comment by jovst** [comment]
> I think you need to update llama_cpp_python to 0.2.79
> 
> https://github.com/instructlab/instructlab/blob/c6adcb5ddd84d9358a2db56c5f30b237420f9b13/requirements.txt#L15
> 
> This is newer than the version in InstructLab 0.17.1: 0.2.75.

Yes thank you very much, saved me a lot of time mate,the model is running now!

I'm still wondering something, I've normally done all the steps in the README on my Ubuntu machine, shouldn't the packages default actually fit, I haven't customized anything.
I also got an error message when updating the package that 17.1 needs version 0.2.75, but it still works.

Here is the output:

```
  Building wheel for llama_cpp_python (pyproject.toml) ... done
  Created wheel for llama_cpp_python: filename=llama_cpp_python-0.2.79-cp310-cp310-linux_x86_64.whl size=3689960 sha256=af63db39e5671134d1cc3a86ba8a3e4f1af99b13387983827728b04556c4fb6f
  Stored in directory: /root/.cache/pip/wheels/bb/2e/11/8b10c6b698e6abc1289e9919e098ac4bcf6b16ebd46153e8ba
Successfully built llama_cpp_python
Installing collected packages: llama_cpp_python
  Attempting uninstall: llama_cpp_python
    Found existing installation: llama_cpp_python 0.2.75
    Uninstalling llama_cpp_python-0.2.75:
      Successfully uninstalled llama_cpp_python-0.2.75
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
instructlab 0.17.1 requires llama-cpp-python[server]==0.2.75, but you have llama-cpp-python 0.2.79 which is incompatible.
Successfully installed llama_cpp_python-0.2.79
(venv) root@user:/home/user/instructlab# ilab model serve --model-path models/granite-8b-code-instruct.Q4_K_M.gguf
INFO 2024-07-22 21:09:22,981 serve.py:51: serve Using model 'models/granite-8b-code-instruct.Q4_K_M.gguf' with -1 gpu-layers and 4096 max context size.
INFO 2024-07-22 21:09:36,347 server.py:218: server Starting server process, press CTRL+C to shutdown server...
INFO 2024-07-22 21:09:36,351 server.py:219: server After application startup complete see http://127.0.0.1:8000/docs for API.

```

Maybe there is a deeper problem, I wonder how this can happen, i am not very familar with python but this behaviour seems not correct for me

**Comment by bjhargrave** [comment]
InstructLab 0.17.1 does indeed require llama_cpp_python 0.2.75. But that does not support your model. After 0.17.1 was released, the llama_cpp_python dependency was updated to 0.2.79. You have modified the default 0.17.1 installation to use a later version of llama_cpp_python which is the reason for the pip messages. But you get to load your model... :-)
