### ISSUE TITLE
`pip install instructlab[cuda]==0.18.0a4` fails in flash-attn

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#1821]
**Describe the bug**
InstructLab 0.18 now has a hardware-specific optional dependency to install InstructLab for CUDA. However `pip install instructlab[cuda]==0.18.0a4` fails to install in a fresh virtual env due to a bug in flash-attn.

**To Reproduce**
`pip install instructlab[cuda]==0.18.0a4`

**Expected behavior**
Comamand install InstructLab CLI correctly with all CUDA dependencies

**Screenshots**
```console
$ pip install instructlab-training[cuda]
Collecting instructlab-training[cuda]
  Obtaining dependency information for instructlab-training[cuda] from https://files.pythonhosted.org/packages/8e/30/a363c6e568e7d87b871ffa25757c223b6c61efb4c0fabeb0bdd4da676112/instructlab_training-0.3.0-py3-none-any.whl.metadata
...
Collecting flash-attn>=2.4.0 (from instructlab-training[cuda])
  Using cached flash_attn-2.6.1.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "venv/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "venv/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "venv/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-g9_133ri/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-g9_133ri/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-g9_133ri/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-g9_133ri/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 19, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Device Info (please complete the following information):**
 - InstructLab Version: 0.18.0a4

**Additional context**
see
- https://github.com/instructlab/training/issues/147
- https://github.com/Dao-AILab/flash-attention/pull/958

**Comment by nathan-weinberg** [comment]
@ktam3 @courtneypacheco let's see if we can prioritize this after feature freeze - we may be able to simplify our CI installation steps if this is no longer an issue: https://github.com/instructlab/instructlab/blob/main/.github/workflows/e2e-nvidia-l40s-x4.yml#L140C13-L140C67

**Comment by booxter** [comment]
There's a proposal for flash_attn to fix this here: https://github.com/Dao-AILab/flash-attention/pull/958 (from our own Doug H). In the meantime, it's not clear what we can do except pre-installing dependencies for them...
