### ISSUE TITLE
TypeError when training microsoft/phi-2 model

### ISSUE THREAD

**Issue by svghadi** [instructlab/instructlab#1935]
**Describe the bug**
I am trying to fine tune `phi-2` model on custom dataset using `ilab model train` command. The command downloads the model successfully from huggingface however it later fails with `TypeError: argument 'folder': 'PosixPath' object cannot be converted to 'PyString'` error. I am on Mac M1.
<details>
  <summary><b>Full log</b></summary>

    ```
    (venv) sghadi-mac:argocd-data sghadi$ ilab model train --iters 50 --model-dir microsoft/phi-2 --model-name microsoft/phi-2
    [INFO] Loading
    Fetching 10 files: 100%|█████████████████████████████████| 10/10 [00:00<00:00, 6049.77it/s]
    /Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
      warnings.warn(
    Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
    dtype=mlx.core.float16
    [INFO] Quantizing
    Using model_type='phi'
    Traceback (most recent call last):
      File "/Users/sghadi/Documents/source-code/argocd-data/venv/bin/ilab", line 8, in <module>
        sys.exit(ilab())
                 ^^^^^^
      File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
        return self.main(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
        rv = self.invoke(ctx)
             ^^^^^^^^^^^^^^^^
      File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
        return ctx.invoke(self.callback, **ctx.params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
        return __callback(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
        return f(get_current_context(), *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/instructlab/model/train.py", line 345, in train
        convert_between_mlx_and_pytorch(
      File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/instructlab/train/lora_mlx/convert.py", line 81, in convert_between_mlx_and_pytorch
        utils.save_model(mlx_path, weights, tokenizer, config)
      File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/instructlab/train/lora_mlx/utils.py", line 155, in save_model
        tokenizer.save_vocabulary(save_dir_path)
      File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/transformers/models/codegen/tokenization_codegen_fast.py", line 181, in save_vocabulary
        files = self._tokenizer.model.save(save_directory, name=filename_prefix)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: argument 'folder': 'PosixPath' object cannot be converted to 'PyString'
    ```

</details>

**To Reproduce**
Train `microsoft/phi-2` model using
```
ilab model train --iters 50 --model-dir microsoft/phi-2 --model-name microsoft/phi-2
```

**Expected behavior**

Training should complete without any errors.

**Device Info (please complete the following information):**
 - Hardware Specs: Apple M1 Pro Chip, 32 GB Memory
 - OS Version: Mac OS 14.5
 - Python Version: Python 3.11.7
 - InstructLab Version: ilab, version 0.17.1

**Comment by bjhargrave** [comment]
Yes, I have encountered this too. 

See if this patch fixes it for you. If it does, I can make a PR.

```diff
diff --git a/src/instructlab/train/lora_mlx/utils.py b/src/instructlab/train/lora_mlx/utils.py
index d5534e4..2e29ece 100644
--- a/src/instructlab/train/lora_mlx/utils.py
+++ b/src/instructlab/train/lora_mlx/utils.py
@@ -152,7 +152,7 @@ def save_model(save_dir: str, weights, tokenizer, config):
         )

     tokenizer.save_pretrained(save_dir_path)
-    tokenizer.save_vocabulary(save_dir_path)
+    tokenizer.save_vocabulary(str(save_dir_path))

     with open(save_dir_path / "config.json", "w") as fid:
         json.dump(config, fid, indent=4)
```

**Comment by svghadi** [comment]
Thanks @bjhargrave. After applying your patch the training **completes successfully**. However, I am now running into issues for `ilab model convert` command.

```
(venv) sghadi-mac:argocd-data sghadi$ ilab model convert --model-dir microsoft-phi-2-mlx-q
Loading pretrained model
Using model_type='phi'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 2024-08-01 11:52:56,846 convert.py:83: convert deleting microsoft-phi-2-mlx-q...
[INFO] Loading
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
dtype=<class 'numpy.float16'>
INFO 2024-08-01 11:53:05,590 convert.py:92: convert deleting microsoft-phi-2-mlx-q-fused...
Loading model file microsoft-phi-2-trained/model.safetensors
Traceback (most recent call last):
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/instructlab/utils.py", line 60, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/instructlab/model/convert.py", line 95, in convert
    convert_llama_to_gguf(
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/instructlab/llamacpp/llamacpp_convert_to_gguf.py", line 1674, in convert_llama_to_gguf
    params = Params.load(model_plus)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/instructlab/llamacpp/llamacpp_convert_to_gguf.py", line 370, in load
    params = Params.loadHFTransformerJson(model_plus.model, hf_config_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sghadi/Documents/source-code/argocd-data/venv/lib/python3.11/site-packages/instructlab/llamacpp/llamacpp_convert_to_gguf.py", line 309, in loadHFTransformerJson
    f_norm_eps=config["rms_norm_eps"],
               ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'rms_norm_eps'
```
