### ISSUE TITLE
ilab serve cannot start: ValueError: Unable to configure handler 'vllm'

### ISSUE THREAD

**Issue by ktam3** [instructlab/instructlab#1988]
Qcow2 Bootc image : quay.io/redhat-user-workloads/rhel-ai-tenant/disk-images/nvidia-bootc-disk-image:4c0064a3546b643d26480531a1933a4be5557150-qcow2-amd64

instructlab image: quay.io/redhat-user-workloads/rhel-ai-tenant/rhel-ai-1-1/instructlab-nvidia:2b39b651893ce8012e9d86c966cc96e8a2326fa5

`$ ilab --version
ilab, version 0.18.0b6`

Updated config file to use

ilab model download --repository=instructlab/granite-7b-lab

> $ ilab model serve --model-path ~/.cache/instructlab/models/instructlab/granite-7b-lab/
DEBUG 2024-08-06 14:50:29,547 git.cmd:1253: Popen(['git', 'version'], cwd=/instructlab, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-08-06 14:50:29,550 git.cmd:1253: Popen(['git', 'version'], cwd=/instructlab, stdin=None, shell=False, universal_newlines=False)
Parameters:
     model_path: PosixPath('/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab')     [type: pathlib.PosixPath, src: commandline]
     gpu_layers: -1           [type: int, src: default_map]
    num_threads: None         [type: None, src: default]
   max_ctx_size: 4096         [type: int, src: default_map]
   model_family: None         [type: None, src: default]
       log_file: None         [type: None, src: default]
  chat_template: None         [type: None, src: default]
        backend: None         [type: None, src: default]
DEBUG 2024-08-06 14:50:30,364 instructlab.model.backends.backends:248: Auto-detecting backend for model /var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab
DEBUG 2024-08-06 14:50:30,401 instructlab.model.backends.backends:206: Model is huggingface safetensors and system is Linux, using vllm backend.
DEBUG 2024-08-06 14:50:30,401 instructlab.model.backends.backends:256: Auto-detected backend: vllm
DEBUG 2024-08-06 14:50:30,401 instructlab.model.backends.backends:261: Backend is not set using auto-detected value: vllm
INFO 2024-08-06 14:50:30,401 instructlab.model.serve:136: Using model '/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab' with -1 gpu-layers and 4096 max context size.
INFO 2024-08-06 14:50:30,401 instructlab.model.serve:140: Serving model '/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab' with vllm
DEBUG 2024-08-06 14:50:30,401 instructlab.model.backends.backends:388: Searching hard coded model templates for model family merlinite's template
DEBUG 2024-08-06 14:50:30,401 instructlab.model.backends.vllm:188: vLLM serving command is: ['/opt/app-root/bin/python3.11', '-m', 'vllm.entrypoints.openai.api_server', '--host', '127.0.0.1', '--port', '8000', '--model', '/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab', '--chat-template', '/tmp/tmpo_14aagi', '--distributed-executor-backend', 'mp']
INFO 2024-08-06 14:50:30,402 instructlab.model.backends.vllm:200: vLLM starting up on pid 34 at http://127.0.0.1:8000/v1
Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/config.py", line 573, in configure
    handler = self.configure_handler(handlers[name])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/config.py", line 770, in configure_handler
    result.setLevel(logging._checkLevel(level))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 207, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/opt/app-root/lib64/python3.11/site-packages/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/opt/app-root/lib64/python3.11/site-packages/vllm/engine/arg_utils.py", line 7, in <module>
    from vllm.config import (CacheConfig, DecodingConfig, DeviceConfig,
  File "/opt/app-root/lib64/python3.11/site-packages/vllm/config.py", line 9, in <module>
    from vllm.logger import init_logger
  File "/opt/app-root/lib64/python3.11/site-packages/vllm/logger.py", line 91, in <module>
    _configure_vllm_root_logger()
  File "/opt/app-root/lib64/python3.11/site-packages/vllm/logger.py", line 77, in _configure_vllm_root_logger
    dictConfig(logging_config)
  File "/usr/lib64/python3.11/logging/config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib64/python3.11/logging/config.py", line 580, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'vllm'

This is happening on IBM L40S system:

> [cloud-user@ecosystem-qe-auto instructlab]$ nvidia-smi 
Tue Aug  6 14:54:35 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L40S                    On  |   00000000:04:01.0 Off |                    0 |
| N/A   36C    P8             32W /  350W |       1MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA L40S                    On  |   00000000:04:02.0 Off |                    0 |
| N/A   33C    P8             24W /  350W |       1MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

**Comment by ktam3** [comment]
Constantin:
As root, started the following command: (based on discussions with @alimaredia )

> podman run  --uidmap 0:1000 --uidmap 1:100000:65536 --device nvidia.com/gpu=all --security-opt label=disable --net host --shm-size 10G -v /var/home/cloud-user:/var/home/cloud-user -v /run/user/1000/containers/auth.json:/run/containers/0/auth.json -it quay.io/redhat-user-workloads/rhel-ai-tenant/rhel-ai-1-1/instructlab-nvidia:2b39b651893ce8012e9d86c966cc96e8a2326fa5  /bin/sh

and inside the contaniner ran:

> [root@pytorch instructlab]# /opt/app-root/bin/python3.11 -m vllm.entrypoints.openai.api_server --host 127.0.0.1 --port 8000 --model /var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab

which gave:

> /opt/app-root/lib64/python3.11/site-packages/vllm/usage/usage_lib.py:19: RuntimeWarning: Failed to read commit hash:
No module named 'vllm.commit_id'
  from vllm.version import __version__ as VLLM_VERSION
INFO 08-06 15:13:32 api_server.py:212] vLLM API server version 0.5.2.2
INFO 08-06 15:13:32 api_server.py:213] args: Namespace(host='127.0.0.1', port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, model_loader_extra_config=None, preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
INFO 08-06 15:13:32 config.py:1375] Downcasting torch.float32 to torch.float16.
INFO 08-06 15:13:32 llm_engine.py:174] Initializing an LLM engine (v0.5.2.2) with config: model='/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab', speculative_config=None, tokenizer='/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab, use_v2_block_manager=False, enable_prefix_caching=False)
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
INFO 08-06 15:13:36 model_runner.py:266] Loading model weights took 12.5532 GB
INFO 08-06 15:13:37 gpu_executor.py:86] # GPU blocks: 3434, # CPU blocks: 512
INFO 08-06 15:13:40 model_runner.py:1007] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 08-06 15:13:40 model_runner.py:1011] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 08-06 15:13:51 model_runner.py:1208] Graph capturing finished in 11 secs.
WARNING 08-06 15:13:51 serving_embedding.py:138] embedding_mode is False. Embedding API will not work.
INFO 08-06 15:13:51 api_server.py:257] Available routes are:
INFO 08-06 15:13:51 api_server.py:262] Route: /openapi.json, Methods: HEAD, GET
INFO 08-06 15:13:51 api_server.py:262] Route: /docs, Methods: HEAD, GET
INFO 08-06 15:13:51 api_server.py:262] Route: /docs/oauth2-redirect, Methods: HEAD, GET
INFO 08-06 15:13:51 api_server.py:262] Route: /redoc, Methods: HEAD, GET
INFO 08-06 15:13:51 api_server.py:262] Route: /health, Methods: GET
INFO 08-06 15:13:51 api_server.py:262] Route: /tokenize, Methods: POST
INFO 08-06 15:13:51 api_server.py:262] Route: /detokenize, Methods: POST
INFO 08-06 15:13:51 api_server.py:262] Route: /v1/models, Methods: GET
INFO 08-06 15:13:51 api_server.py:262] Route: /version, Methods: GET
INFO 08-06 15:13:51 api_server.py:262] Route: /v1/chat/completions, Methods: POST
INFO 08-06 15:13:51 api_server.py:262] Route: /v1/completions, Methods: POST
INFO 08-06 15:13:51 api_server.py:262] Route: /v1/embeddings, Methods: POST
INFO:     Started server process [104]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO 08-06 15:14:01 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 08-06 15:14:11 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 08-06 15:14:21 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 08-06 15:14:31 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 08-06 15:14:41 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 08-06 15:14:51 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 08-06 15:15:01 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.

Then ran ilab inside the container:

> [root@pytorch instructlab]# ilab serve --model-path /var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab
You are using an aliased command, this will be deprecated in a future release. Please consider using `ilab model serve` instead
INFO 2024-08-06 15:16:39,968 instructlab.model.serve:136: Using model '/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab' with -1 gpu-layers and 4096 max context size.
INFO 2024-08-06 15:16:39,969 instructlab.model.serve:140: Serving model '/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab' with vllm
INFO 2024-08-06 15:16:39,969 instructlab.model.backends.vllm:200: vLLM starting up on pid 187 at http://127.0.0.1:8000/v1
/opt/app-root/lib64/python3.11/site-packages/vllm/usage/usage_lib.py:19: RuntimeWarning: Failed to read commit hash:
No module named 'vllm.commit_id'
  from vllm.version import __version__ as VLLM_VERSION
INFO 08-06 15:16:42 api_server.py:212] vLLM API server version 0.5.2.2
INFO 08-06 15:16:42 api_server.py:213] args: Namespace(host='127.0.0.1', port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template='/tmp/tmpgpxf5llg', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend='mp', worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, model_loader_extra_config=None, preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
INFO 08-06 15:16:42 config.py:1375] Downcasting torch.float32 to torch.float16.
INFO 08-06 15:16:42 llm_engine.py:174] Initializing an LLM engine (v0.5.2.2) with config: model='/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab', speculative_config=None, tokenizer='/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/var/home/cloud-user/.cache/instructlab/models/instructlab/granite-7b-lab, use_v2_block_manager=False, enable_prefix_caching=False)
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
INFO 08-06 15:16:50 model_runner.py:266] Loading model weights took 12.5532 GB
INFO 08-06 15:16:51 distributed_gpu_executor.py:56] # GPU blocks: 3434, # CPU blocks: 512
INFO 08-06 15:16:53 model_runner.py:1007] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 08-06 15:16:53 model_runner.py:1011] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 08-06 15:17:03 model_runner.py:1208] Graph capturing finished in 10 secs.
INFO 08-06 15:17:03 serving_chat.py:94] Using supplied chat template:
INFO 08-06 15:17:03 serving_chat.py:94] {% set eos_token = "<|endoftext|>" %}
INFO 08-06 15:17:03 serving_chat.py:94] {% for message in messages %}
INFO 08-06 15:17:03 serving_chat.py:94] {% if message['role'] == 'user' %}
INFO 08-06 15:17:03 serving_chat.py:94] {{ '<|user|>
INFO 08-06 15:17:03 serving_chat.py:94] ' + message['content'] }}
INFO 08-06 15:17:03 serving_chat.py:94] {% elif message['role'] == 'system' %}
INFO 08-06 15:17:03 serving_chat.py:94] {{ '<|system|>
INFO 08-06 15:17:03 serving_chat.py:94] ' + message['content'] }}
INFO 08-06 15:17:03 serving_chat.py:94] {% elif message['role'] == 'assistant' %}
INFO 08-06 15:17:03 serving_chat.py:94] {{ '<|assistant|>
INFO 08-06 15:17:03 serving_chat.py:94] ' + message['content'] + eos_token }}
INFO 08-06 15:17:03 serving_chat.py:94] {% endif %}
INFO 08-06 15:17:03 serving_chat.py:94] {% if loop.last and add_generation_prompt %}
INFO 08-06 15:17:03 serving_chat.py:94] {{ '<|assistant|>' }}
INFO 08-06 15:17:03 serving_chat.py:94] {% endif %}
INFO 08-06 15:17:03 serving_chat.py:94] {% endfor %}
WARNING 08-06 15:17:03 serving_embedding.py:138] embedding_mode is False. Embedding API will not work.
INFO 08-06 15:17:03 api_server.py:257] Available routes are:
INFO 08-06 15:17:03 api_server.py:262] Route: /openapi.json, Methods: GET, HEAD
INFO 08-06 15:17:03 api_server.py:262] Route: /docs, Methods: GET, HEAD
INFO 08-06 15:17:03 api_server.py:262] Route: /docs/oauth2-redirect, Methods: GET, HEAD
INFO 08-06 15:17:03 api_server.py:262] Route: /redoc, Methods: GET, HEAD
INFO 08-06 15:17:03 api_server.py:262] Route: /health, Methods: GET
INFO 08-06 15:17:03 api_server.py:262] Route: /tokenize, Methods: POST
INFO 08-06 15:17:03 api_server.py:262] Route: /detokenize, Methods: POST
INFO 08-06 15:17:03 api_server.py:262] Route: /v1/models, Methods: GET
INFO 08-06 15:17:03 api_server.py:262] Route: /version, Methods: GET
INFO 08-06 15:17:03 api_server.py:262] Route: /v1/chat/completions, Methods: POST
INFO 08-06 15:17:03 api_server.py:262] Route: /v1/completions, Methods: POST
INFO 08-06 15:17:03 api_server.py:262] Route: /v1/embeddings, Methods: POST
INFO:     Started server process [187]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)

**Comment by ktam3** [comment]
Ariel: 
Confirming this happens also on bm:

[auser@nvd-srv-03 roothome]$ sudo bootc status
apiVersion: org.containers.bootc/v1alpha1
kind: BootcHost
metadata:
  name: host
spec:
  image:
    image: quay.io/redhat-user-workloads/rhel-ai-tenant/rhel-ai-1-1/nvidia-bootc:b3cbb5c740e4c07e5160b6dfc1861d4b71bf7858
    transport: registry
  bootOrder: default
status:
  staged: null
  booted:
    image:
      image:
        image: quay.io/redhat-user-workloads/rhel-ai-tenant/rhel-ai-1-1/nvidia-bootc:b3cbb5c740e4c07e5160b6dfc1861d4b71bf7858
        transport: registry
      version: 9.20240729.0
      timestamp: null
      imageDigest: sha256:4568d3f252f012ba3246a04e0f9bb80b8128f2ed103f924cd09360aa58da9eff
    cachedUpdate: null
    incompatible: false
    pinned: false
    ostree:
      checksum: df2b90c96ed615ab6fb745fb9befc6dd9d33995f6e87edd6cbf09c294ddef7ce
      deploySerial: 0
  rollback:
    image:
      image:
        image: registry.redhat.io/rhelai1/bootc-nvidia-rhel9:1.1
        transport: registry
      version: 9.20240729.0
      timestamp: null
      imageDigest: sha256:22ab7f66d96a16ac2943d2d0c23b7123d15610faf184238ed804e1663a347159
    cachedUpdate: null
    incompatible: false
    pinned: false
    ostree:
      checksum: 66d48ee13c43051147cf13c3973f44a2cd47d921d5225ec0113586d44db4a584
      deploySerial: 0
  rollbackQueued: false
  type: bootcHost

`[auser@nvd-srv-03 roothome]$ ilab model serve --model-family granite --model-path /home/auser/.cache/instructlab/models/granite
[sudo] password for auser:
INFO 2024-08-06 15:45:03,942 instructlab.model.serve:136: Using model '/home/auser/.cache/instructlab/models/granite' with -1 gpu-layers and 4096 max context size.
INFO 2024-08-06 15:45:03,942 instructlab.model.serve:140: Serving model '/home/auser/.cache/instructlab/models/granite' with vllm
INFO 2024-08-06 15:45:03,942 instructlab.model.backends.vllm:200: vLLM starting up on pid 28 at http://127.0.0.1:8000/v1
Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/config.py", line 573, in configure
    handler = self.configure_handler(handlers[name])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/config.py", line 770, in configure_handler
    result.setLevel(logging._checkLevel(level))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 207, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/opt/app-root/lib64/python3.11/site-packages/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/opt/app-root/lib64/python3.11/site-packages/vllm/engine/arg_utils.py", line 7, in <module>
    from vllm.config import (CacheConfig, DecodingConfig, DeviceConfig,
  File "/opt/app-root/lib64/python3.11/site-packages/vllm/config.py", line 9, in <module>
    from vllm.logger import init_logger
  File "/opt/app-root/lib64/python3.11/site-packages/vllm/logger.py", line 91, in <module>
    _configure_vllm_root_logger()
  File "/opt/app-root/lib64/python3.11/site-packages/vllm/logger.py", line 77, in _configure_vllm_root_logger
    dictConfig(logging_config)
  File "/usr/lib64/python3.11/logging/config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib64/python3.11/logging/config.py", line 580, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'vllm'`

**Comment by ktam3** [comment]
Per conversation in slack channel - This seems to only be an issue downstream. No upstream fix needed.
