### ISSUE TITLE
Potentially incompatible version of instructlab-sdg being installed

### ISSUE THREAD

**Issue by chrismarth** [instructlab/instructlab#2138]
**Describe the bug**
After following the installation instructions for Mac (Apple Metal) on the 'Getting Started' I try to do SDG and see this:

```
$ ilab data generate
INFO 2024-08-22 13:45:45,012 numexpr.utils:161: NumExpr defaulting to 12 threads.
INFO 2024-08-22 13:45:45,213 datasets:59: PyTorch version 2.3.1 available.
INFO 2024-08-22 13:45:45,679 instructlab.model.backends.llama_cpp:104: Trying to connect to model server at http://127.0.0.1:8000/v1
WARNING 2024-08-22 13:45:45,693 instructlab.data.generate:291: Disabling SDG batching - unsupported with llama.cpp serving
Generating synthetic data using 'simple' pipeline, '/Users/racerx/Library/Caches/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf' model, '/Users/racerx/Library/Application Support/instructlab/taxonomy' taxonomy, against http://127.0.0.1:8000/v1 server
Traceback (most recent call last):
  File "/opt/anaconda3/envs/instructLab/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/opt/anaconda3/envs/instructlab/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/instructlab/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/instructlab/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/instructlab/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/instructlab/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/instructlab/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/instructlab/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/instructlab/lib/python3.11/site-packages/instructlab/clickext.py", line 306, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/instructlab/lib/python3.11/site-packages/instructlab/data/generate.py", line 305, in generate
    generate_data(
TypeError: generate_data() got an unexpected keyword argument 'api_base'
```

My setup is as follows:
```
$ ilab system info
sys.version: 3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ]
sys.platform: darwin
os.name: posix
platform.release: 23.6.0
platform.machine: arm64
platform.node: shootingstar-2.local
platform.python_version: 3.11.9
instructlab.version: 0.18.2
instructlab-dolomite.version: 0.1.1
instructlab-eval.version: 0.1.1
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.4.1
instructlab-sdg.version: 0.3.0
instructlab-training.version: 0.4.2
torch.version: 2.3.1
torch.backends.cpu.capability: NO AVX
torch.version.cuda: None
torch.version.hip: None
torch.cuda.available: False
torch.backends.cuda.is_built: False
torch.backends.mps.is_built: True
torch.backends.mps.is_available: True
llama_cpp_python.version: 0.2.79
llama_cpp_python.supports_gpu_offload: True
```

Looking at this, I noticed the latest version of `instruct-sdg` being installed.  If I go to my Windows/WSL machine (which performs SDG wo/ issue), I see this system setup for the same version of `ilab`:

```
ilab system info
sys.version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
sys.platform: linux
os.name: posix
platform.release: 5.15.153.1-microsoft-standard-WSL2
platform.machine: x86_64
platform.node: augury
platform.python_version: 3.11.9
os-release.ID: ubuntu
os-release.VERSION_ID: 22.04
os-release.PRETTY_NAME: Ubuntu 22.04.4 LTS
instructlab.version: 0.18.1
instructlab-dolomite.version: 0.1.1
instructlab-eval.version: 0.1.1
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.4.0
instructlab-sdg.version: 0.2.6
instructlab-training.version: 0.4.2
torch.version: 2.3.1+cu121
torch.backends.cpu.capability: AVX2
torch.version.cuda: 12.1
torch.version.hip: None
torch.cuda.available: True
torch.backends.cuda.is_built: True
torch.backends.mps.is_built: False
torch.backends.mps.is_available: False
torch.cuda.bf16: True
torch.cuda.current.device: 0
torch.cuda.0.name: NVIDIA GeForce RTX 3070
torch.cuda.0.free: 6.9 GB
torch.cuda.0.total: 8.0 GB
torch.cuda.0.capability: 8.6 (see https://developer.nvidia.com/cuda-gpus#compute)
llama_cpp_python.version: 0.2.79
llama_cpp_python.supports_gpu_offload: True
```

Note the difference in the version of `instructlab-sdg`.  If I then go back to my Mac and downgrade `instructlab-sdg` to this same version, generation completes as expected.

I'm not sure if I am setting something up incorrectly, but at least on the surface, it's not obvious why I am getting an incompatible version on the Mac.

**To Reproduce**
1. Go through 'Getting Started' on a Mac
2. Get to point where you try to `ilab data generate` and see error above

**Expected behavior**
The generate command should work as expected.

**Device Info (please complete the following information):**
 - See printout above

**Comment by bjhargrave** [comment]
I don't think you can use `instructlab-sdg.version: 0.3.0` with `instructlab.version: 0.18.2`.

See https://github.com/instructlab/instructlab/pull/2134 which fixed the versions in the release-v0.18 branch. Need to make a 0.18.3 release from that branch.

**Comment by bjhargrave** [comment]
0.18.3 was just released with #2134. Please try that version.

**Comment by jaideepr97** [comment]
@chrismarth we have just released v0.19.0, please try that and let us know if it worked
if It did I would propose to close this issue
