### ISSUE TITLE
ilab cuda containerfile throws `ImportError: libcudnn.so.9: cannot open shared object file: No such file or directory` error

### ISSUE THREAD

**Issue by pacificera** [instructlab/instructlab#2209]
**Describe the bug**
Missing cuda library after succesful container build

**To Reproduce**
I built the containerfile with podman under fedora with success.  I can enter the containerfile with an interactive terminal and issue `nvidia-smi` successfully.  When I issue the `ilab` command, the following error is produced:
``
❯ podman  run -it --rm --security-opt=label=disable    --device=nvidia.com/gpu=all 3b098c5ec284 /bin/bash

==========
== CUDA ==
==========

CUDA Version 12.4.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

[root@4245cf88a6e9 instructlab]# nvidia-smi 
Thu Sep  5 19:41:52 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2070 ...    On  |   00000000:09:00.0  On |                  N/A |
|  0%   54C    P0             52W /  260W |    1401MiB /   8192MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
[root@4245cf88a6e9 instructlab]# ilab
Traceback (most recent call last):
  File "/usr/local/bin/ilab", line 5, in <module>
    from instructlab.lab import ilab
  File "/usr/local/lib/python3.11/site-packages/instructlab/lab.py", line 20, in <module>
    from .model import model as model_group
  File "/usr/local/lib/python3.11/site-packages/instructlab/model/model.py", line 13, in <module>
    from .train import train
  File "/usr/local/lib/python3.11/site-packages/instructlab/model/train.py", line 11, in <module>
    import torch
  File "/usr/local/lib64/python3.11/site-packages/torch/__init__.py", line 290, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcudnn.so.9: cannot open shared object file: No such file or directory
[root@4245cf88a6e9 instructlab]# 

**Expected behavior**
ilab should run without error

**Device Info (please complete the following information):**
I built with the container file with id: 945fd51b47b8f94707c5be6abc6e9ee9aca83227
https://github.com/instructlab/instructlab/commits/main/containers/cuda/Containerfile

**Comment by clopnis** [comment]
it's about a bad LD_LIBRARY_PATH
quick fix with :
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python3.11/site-packages/nvidia/cudnn/lib/
```
