### ISSUE TITLE
EmptyDatasetError on `ilab data generate`

### ISSUE THREAD

**Issue by mdevino** [instructlab/instructlab#2280]
**Describe the bug**
When I run `ilab data generate --gpus=1 --pipeline full` I'm receiving the following error message:

```
instructlab.sdg.pipeline.EmptyDatasetError: Pipeline stopped: Empty dataset after running pipe
```

**To Reproduce**
1. Setup InstructLab (I'm using Python 3.11 with CUDA)
2. Download a model (I'm using the default merlinite)
3. Execute `ilab data generate --gpus=1 --pipeline full`

**Expected behavior**

I would expect the generation to finish successfully.

**Screenshots**

**Device Info (please complete the following information):**
 - Hardware Specs: Intel i9 10900k, RTX 3080, 128GB RAM
 - OS Version: Arch Linux (WSL)
 - Python Version: Python 3.11.10
 - InstructLab Version: [output of `ilab system info`]

sys.version: 3.11.10 (main, Sep 17 2024, 16:16:28) [GCC 14.1.1 20240522]
sys.platform: linux
os.name: posix
platform.release: 5.10.102.1-microsoft-standard-WSL2
platform.machine: x86_64
platform.node: shiny
platform.python_version: 3.11.10
os-release.ID: arch
os-release.PRETTY_NAME: Arch Linux
instructlab.version: 0.18.4
instructlab-dolomite.version: 0.1.1
instructlab-eval.version: 0.1.2
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.3.1
instructlab-sdg.version: 0.2.7
instructlab-training.version: 0.4.2
torch.version: 2.3.1+cu121
torch.backends.cpu.capability: AVX2
torch.version.cuda: 12.1
torch.version.hip: None
torch.cuda.available: True
torch.backends.cuda.is_built: True
torch.backends.mps.is_built: False
torch.backends.mps.is_available: False
torch.cuda.bf16: True
torch.cuda.current.device: 0
torch.cuda.0.name: NVIDIA GeForce RTX 3080
torch.cuda.0.free: 8.9 GB
torch.cuda.0.total: 10.0 GB
torch.cuda.0.capability: 8.6 (see https://developer.nvidia.com/cuda-gpus#compute)
llama_cpp_python.version: 0.2.79
llama_cpp_python.supports_gpu_offload: True

**Additional context**

My taxonomy only have skill (no knowledge). Would this be a problem?

**Comment by aseelert** [comment]
**Same for me in Redhat 9.2**


`Traceback (most recent call last):
  File "/home/itzuser/instructlab/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/home/itzuser/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itzuser/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/itzuser/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itzuser/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itzuser/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itzuser/instructlab/venv/lib64/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itzuser/instructlab/venv/lib64/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itzuser/instructlab/venv/lib64/python3.11/site-packages/instructlab/clickext.py", line 306, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/itzuser/instructlab/venv/lib64/python3.11/site-packages/instructlab/data/generate.py", line 305, in generate
    generate_data(
  File "/home/itzuser/instructlab/venv/lib64/python3.11/site-packages/instructlab/sdg/generate_data.py", line 403, in generate_data
    raise EmptyDatasetError(
instructlab.sdg.pipeline.EmptyDatasetError: Pipeline stopped: Empty dataset after running pipe`


**Folllowing System**
(venv) [itzuser@itzvsi-550001nu41-hsscbt6c datasets]$ ilab system info
sys.version: 3.11.2 (main, Jul 18 2024, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)]
sys.platform: linux
os.name: posix
platform.release: 5.14.0-284.82.1.el9_2.x86_64
platform.machine: x86_64
platform.node: itzvsi-550001nu41-hsscbt6c
platform.python_version: 3.11.2
os-release.ID: rhel
os-release.VERSION_ID: 9.2
os-release.PRETTY_NAME: Red Hat Enterprise Linux 9.2 (Plow)
instructlab.version: 0.18.4
instructlab-dolomite.version: 0.1.1
instructlab-eval.version: 0.1.2
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.3.1
instructlab-sdg.version: 0.2.7
instructlab-training.version: 0.4.2
torch.version: 2.3.1+cu121
torch.backends.cpu.capability: AVX512
torch.version.cuda: 12.1
torch.version.hip: None
torch.cuda.available: True
torch.backends.cuda.is_built: True
torch.backends.mps.is_built: False
torch.backends.mps.is_available: False
torch.cuda.bf16: True
torch.cuda.current.device: 0
torch.cuda.0.name: NVIDIA L4
torch.cuda.0.free: 7.0 GB
torch.cuda.0.total: 22.1 GB
torch.cuda.0.capability: 8.9 (see https://developer.nvidia.com/cuda-gpus#compute)
llama_cpp_python.version: 0.2.90
llama_cpp_python.supports_gpu_offload: True

**Comment by aseelert** [comment]
For 
**Serve**
`ilab model serve --gpus 1 --gpu-layers -1 --backend llama-cpp --model-path ./.cache/instructlab/models/mixtral-8x7b-instruct-v0.1.Q3_K_M.gguf`

**Generate**
`ilab data generate --pipeline full --gpus 1 --num-cpus 16 --sdg-scale-factor 500 --output-dir /home/itzuser/.local/share/instructlab/generated_data_500`

**Comment by mdevino** [comment]
Using the simple pipeline worked for me:

```
ilab data generate --gpus=1 --pipeline simple
```
