### ISSUE TITLE
AssertionError Exception: from await original_route_handler(request)

### ISSUE THREAD

**Issue by pvrbharg** [instructlab/instructlab#2333]
**Describe the bug**

I am trying to run the command ilab data generate --taxonomy-path ./taxonomy when I am getting this error

**To Reproduce**
Setup ilab with latest release version on a RHEL 9.4 instance and perform the data generate step as shown above.
Use this developer article if needed:  https://developer.ibm.com/tutorials/awb-contributing-knowledge-instructlab-granite/
**Expected behavior**

Data generation step succeeding.

**Screenshots**

![ILAB_CLIENT_CONSOLE_SCREENSHOT](https://github.com/user-attachments/assets/20d07f3c-3335-4b44-9ce7-dfcb80eb63ff)
![ILAB_SERVER_ERROR_SCREENSHOT](https://github.com/user-attachments/assets/8b1d97e8-7e2f-48ca-a8fa-835e582813d5)
[ILAB_CLIENT_CONSOLE.txt](https://github.com/user-attachments/files/17167688/ILAB_CLIENT_CONSOLE.txt)
[ILAB_SERVER_ERROR.txt](https://github.com/user-attachments/files/17167689/ILAB_SERVER_ERROR.txt)

**Device Info (please complete the following information):**
 - Linux itzvsi-100000peue-u2sy5ssf 5.14.0-284.71.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jun 17 10:33:25 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
 -  cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://issues.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
 - Python Version: Python 3.11.2
 - InstructLab Version: [output of `ilab system info`]
   ilab, version 0.18.4
   sys.version: 3.11.2 (main, Jul 18 2024, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)]
sys.platform: linux
os.name: posix
platform.release: 5.14.0-284.71.1.el9_2.x86_64
platform.machine: x86_64
platform.node: itzvsi-100000peue-u2sy5ssf
platform.python_version: 3.11.2
os-release.ID: rhel
os-release.VERSION_ID: 9.2
os-release.PRETTY_NAME: Red Hat Enterprise Linux 9.2 (Plow)
instructlab.version: 0.18.4
instructlab-dolomite.version: 0.1.1
instructlab-eval.version: 0.1.2
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.3.1
instructlab-sdg.version: 0.2.7
instructlab-training.version: 0.4.2
torch.version: 2.3.1+cu121
torch.backends.cpu.capability: AVX512
torch.version.cuda: 12.1
torch.version.hip: None
torch.cuda.available: False
torch.backends.cuda.is_built: True
torch.backends.mps.is_built: False
torch.backends.mps.is_available: False
llama_cpp_python.version: 0.2.79
llama_cpp_python.supports_gpu_offload: False

**Additional context**

I can provide my qna.yaml and attribution.txt files - which validate if need be.

**Comment by beakly** [comment]
Getting this bug too on InstructLab 0.19.1 when calling `ilab data generate`

Process just hangs and does nothing after creating a test dataset named test_modelname_timestamp.jsonl

`ilab system info` printout:
- sys.version: 3.11.10 (main, Sep  7 2024, 01:03:31) [Clang 16.0.0 (clang-1600.0.26.3)]
- sys.platform: darwin
- os.name: posix
- platform.release: 24.0.0
- platform.machine: arm64
- platform.node: xxx
- platform.python_version: 3.11.10
- platform.cpu_brand: Apple M2
- instructlab.version: 0.19.1
- instructlab-dolomite.version: 0.1.1
- instructlab-eval.version: 0.3.1
- instructlab-quantize.version: 0.1.0
- instructlab-schema.version: 0.4.1
- instructlab-sdg.version: 0.3.0
- instructlab-training.version: 0.5.2
- torch.version: 2.3.1
- torch.backends.cpu.capability: NO AVX
- torch.version.cuda: None
- torch.version.hip: None
- torch.cuda.available: False
- torch.backends.cuda.is_built: False
- torch.backends.mps.is_built: True
- torch.backends.mps.is_available: True
- llama_cpp_python.version: 0.2.79
- llama_cpp_python.supports_gpu_offload: True

Full output of error:
```
(venv) xxx@xxx instructlab % ilab data generate
INFO 2024-10-05 09:46:27,892 numexpr.utils:161: NumExpr defaulting to 8 threads.
INFO 2024-10-05 09:46:30,362 datasets:59: PyTorch version 2.3.1 available.
INFO 2024-10-05 09:46:33,352 instructlab.model.backends.llama_cpp:100: Trying to connect to model server at http://127.0.0.1:8000/v1
WARNING 2024-10-05 09:46:36,159 instructlab.data.generate:270: Disabling SDG batching - unsupported with llama.cpp serving
Generating synthetic data using 'simple' pipeline, '/Users/xxx/.cache/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf' model, './taxonomy' taxonomy, against http://127.0.0.1:62334/v1 server
INFO 2024-10-05 09:46:37,625 instructlab.sdg.generate_data:358: Synthesizing new instructions. If you aren't satisfied with the generated instructions, interrupt training (Ctrl-C) and try adjusting your YAML files. Adding more examples may help.
INFO 2024-10-05 09:46:37,637 instructlab.sdg.pipeline:153: Running pipeline single-threaded
Exception: 
Traceback (most recent call last):
  File "/Users/xxx/repos/instructlab/venv/lib/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/repos/instructlab/venv/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/repos/instructlab/venv/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/repos/instructlab/venv/lib/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception: 
Traceback (most recent call last):
  File "/Users/xxx//repos/instructlab/venv/lib/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/repos/instructlab/venv/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/repos/instructlab/venv/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/repos/instructlab/venv/lib/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception: 
Traceback (most recent call last):
  File "/Users/xxx/repos/instructlab/venv/lib/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/repos/instructlab/venv/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/repos/instructlab/venv/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/repos/instructlab/venv/lib/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
INFO 2024-10-05 09:46:39,023 instructlab.sdg.llmblock:51: LLM server supports batched inputs: False
INFO 2024-10-05 09:46:39,024 instructlab.sdg.pipeline:197: Running block: gen_knowledge
INFO 2024-10-05 09:46:39,024 instructlab.sdg.pipeline:198: Dataset({
    features: ['icl_document', 'document', 'document_outline', 'domain', 'icl_query_1', 'icl_query_2', 'icl_query_3', 'icl_response_1', 'icl_response_2', 'icl_response_3'],
    num_rows: 10
})
```

**Comment by jeffmaury** [comment]
Same with 0.19.3 while exploring UBI9 based InstructLab container for Podman AI Lab integration

**Comment by junaruga** [comment]
I faced this issue on ilab 0.20.1. The log is below.

```
(venv) $ ilab data generate --pipeline simple
INFO 2024-11-08 20:50:57,884 numexpr.utils:161: NumExpr defaulting to 8 threads.
INFO 2024-11-08 20:50:58,437 datasets:59: PyTorch version 2.3.1 available.
INFO 2024-11-08 20:50:59,961 instructlab.model.backends.llama_cpp:125: Trying to connect to model server at http://127.0.0.1:8000/v1
WARNING 2024-11-08 20:51:05,028 instructlab.data.generate_data:72: Disabling SDG batching - unsupported with llama.cpp serving
INFO 2024-11-08 20:51:05,100 instructlab.data.generate_data:82: Generating synthetic data using 'simple' pipeline, '/home/jaruga/.cache/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf' model, '/home/jaruga/.local/share/instructlab/taxonomy' taxonomy, against http://127.0.0.1:41025/v1 server
INFO 2024-11-08 20:51:06,465 instructlab.sdg.generate_data:356: Synthesizing new instructions. If you aren't satisfied with the generated instructions, interrupt training (Ctrl-C) and try adjusting your YAML files. Adding more examples may help.
INFO 2024-11-08 20:51:07,006 instructlab.sdg.checkpointing:59: No existing checkpoints found in /home/jaruga/.local/share/instructlab/datasets/checkpoints/knowledge_technology, generating from scratch
INFO 2024-11-08 20:51:07,006 instructlab.sdg.pipeline:153: Running pipeline single-threaded
Exception:
Traceback (most recent call last):
  File "/home/jaruga/doc/dev/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaruga/doc/dev/instructlab/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaruga/doc/dev/instructlab/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaruga/doc/dev/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception:
Traceback (most recent call last):
  File "/home/jaruga/doc/dev/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaruga/doc/dev/instructlab/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaruga/doc/dev/instructlab/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaruga/doc/dev/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception:
Traceback (most recent call last):
  File "/home/jaruga/doc/dev/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaruga/doc/dev/instructlab/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaruga/doc/dev/instructlab/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaruga/doc/dev/instructlab/venv/lib64/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
INFO 2024-11-08 20:51:09,791 instructlab.sdg.llmblock:52: LLM server supports batched inputs: False
INFO 2024-11-08 20:51:09,791 instructlab.sdg.pipeline:197: Running block: gen_knowledge
INFO 2024-11-08 20:51:09,791 instructlab.sdg.pipeline:198: Dataset({
    features: ['icl_document', 'document', 'document_outline', 'domain', 'icl_query_1', 'icl_query_2', 'icl_query_3', 'icl_response_1', 'icl_response_2', 'icl_response_3'],
    num_rows: 5
})
gen_knowledge Prompt Generation: 41it [14:45, 15.15s/it]
```

**Comment by bbrowning** [comment]
I believe this AssertionError should be fixed in InstructLab 0.21.x or newer by instructlab/sdg#358 and InstructLab 0.21.x pulls in the new enough SDG to have this fix. Has anyone that reported this been able to reproduce with the latest 0.21.x releases?

**Comment by ktam3** [comment]
@pvrbharg - could you test if this is still reproducible in the new ilab release?
