### ISSUE TITLE
Model training fails with 'OverflowError: int too big to convert'

### ISSUE THREAD

**Issue by shaneboulden** [instructlab/instructlab#2544]
**Describe the bug**
I encountered the error "OverflowError: int too big to convert" when trying to run `ilab model train` on my local system.

**To Reproduce**
1. Install `instructlab` with support for CUDA on WSL, following the guide here: https://www.stb.id.au/blog/instructlab-wsl
2. Create a taxonomy file in `~/.local/share/instructlab/taxonomy/compositional_skills/technology/kubernetes/netpol/qna.yaml` with the content here: https://gist.github.com/shaneboulden/a79b4f5d5cb7f38759f026ce6ea4bccd
3. Create synthetic data (`ilab data generate`)
4. Train the model via `ilab model train --device cuda --data-path /home/user/.local/share/instructlab/datasets/skills_train_msgs_2024-10-28T11_35_10.jsonl`

**Expected behavior**
InstructLab runs the training to completion

**Device Info:**
 - Hardware Specs: AMD 5800X3D / NVIDIA RTX 3070 
 - OS Version: Windows subsystem for Linux (WSL), using Fedora 40 image and host NVIDIA GPU driver
 - Python Version: Python 3.11.10
 - InstructLab Version:
```
sys.version: 3.11.10 (main, Sep  9 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)]
sys.platform: linux
os.name: posix
platform.release: 5.15.153.1-microsoft-standard-WSL2
platform.machine: x86_64
platform.node: HelixWin
platform.python_version: 3.11.10
os-release.ID: fedora
os-release.VERSION_ID: 40
os-release.PRETTY_NAME: Fedora Linux 40 (Container Image)
instructlab.version: 0.18.4
instructlab-dolomite.version: 0.1.1
instructlab-eval.version: 0.1.2
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.3.1
instructlab-sdg.version: 0.2.7
instructlab-training.version: 0.4.2
torch.version: 2.3.1+cu121
torch.backends.cpu.capability: AVX2
torch.version.cuda: 12.1
torch.version.hip: None
torch.cuda.available: True
torch.backends.cuda.is_built: True
torch.backends.mps.is_built: False
torch.backends.mps.is_available: False
torch.cuda.bf16: True
torch.cuda.current.device: 0
torch.cuda.0.name: NVIDIA GeForce RTX 3070
torch.cuda.0.free: 6.9 GB
torch.cuda.0.total: 8.0 GB
torch.cuda.0.capability: 8.6 (see https://developer.nvidia.com/cuda-gpus#compute)
llama_cpp_python.version: 0.2.79
llama_cpp_python.supports_gpu_offload: True
```

**Additional context**
The training runs successfully with `--legacy`, i.e.
```
ilab model train --device cuda --data-path /home/user/.local/share/instructlab/datasets/ --legacy
```

Full output of the error is here:
```
$ ilab model train --device cuda --data-path /home/user/.local/share/instructlab/datasets/skills_train_msgs_2024-10-28T11_35_10.jsonl
/home/user/instructlab/venv/lib64/python3.11/site-packages/pydantic/main.py:390: UserWarning: Pydantic serializer warnings:
  Expected `list[str]` but got `tuple` with value `('q_proj', 'k_proj', 'v_proj', 'o_proj')` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
[2024-10-28 13:04:23,359] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
...
...
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
[2024-10-28 13:04:34,327] [INFO] [comm.py:652:init_distributed] cdb=None
[2024-10-28 13:04:34,327] [INFO] [comm.py:683:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Generating train split: 30 examples [00:00, 4173.44 examples/s]
Data length calculation: 100%|██████████| 30/30 [00:00<00:00, 8314.33it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/main_ds.py", line 834, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/main_ds.py", line 522, in main
[rank0]:     packing_max_batch_len, grad_accum = find_packing_max_batch_len_and_grad_accum(
[rank0]:                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/multipack_sampler.py", line 213, in find_packing_max_batch_len_and_grad_accum
[rank0]:     addition = find_padding_max_batch_len_addition(
[rank0]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/multipack_sampler.py", line 138, in find_padding_max_batch_len_addition
[rank0]:     avg_ebs = simulate_buckets(
[rank0]:               ^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/multipack_sampler.py", line 110, in simulate_buckets
[rank0]:     avg_ebs = len(dataset) / len(simulation_loader)
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/torch/utils/data/dataloader.py", line 484, in __len__
[rank0]:     return len(self._index_sampler)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/multipack_sampler.py", line 478, in __len__
[rank0]:     return self.num_batches()
[rank0]:            ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/multipack_sampler.py", line 481, in num_batches
[rank0]:     batches = self.generate_batches()
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/multipack_sampler.py", line 455, in generate_batches
[rank0]:     batches, total_used, total_slots = allocate(
[rank0]:                                        ^^^^^^^^^
[rank0]: OverflowError: int too big to convert
E1028 13:04:45.410000 139639370972032 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 11246) of binary: /home/user/instructlab/venv/bin/python3.11
Traceback (most recent call last):
  File "/home/user/instructlab/venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/instructlab/venv/lib64/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/instructlab/venv/lib64/python3.11/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/user/instructlab/venv/lib64/python3.11/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/user/instructlab/venv/lib64/python3.11/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/instructlab/venv/lib64/python3.11/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/main_ds.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-28_13:04:45
  host      : HelixWin.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 11246)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Operation failed, terminating process.
```

**Comment by alexbarbosa1989** [comment]
I'm getting similar behavior with Instructlab v.0.19.0rc2.dev200 + Python v.3.11.10 + Fedora 40 + NVIDIA GeForce RTX 3060 Ti. 

Here is my command:
~~~
ilab model train --pipeline accelerated --device cuda --data-path /home/user/.local/share/instructlab/datasets/skills_train_msgs_2024-10-29T16_52_10.jsonl
~~~

then got:
~~~
...
Generating train split: 30 examples [00:00, 10332.49 examples/s]
Map (num_proc=8): 100%|██████████| 30/30 [00:00<00:00, 287.81 examples/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/main_ds.py", line 917, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/main_ds.py", line 528, in main
[rank0]:     packing_max_batch_len, grad_accum = find_packing_max_batch_len_and_grad_accum(
[rank0]:                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/multipack_sampler.py", line 160, in find_packing_max_batch_len_and_grad_accum
[rank0]:     packing_max_batch_len = find_max_pack_len_with_padding(
[rank0]:                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/multipack_sampler.py", line 91, in find_max_pack_len_with_padding
[rank0]:     avg_bs_per_minibatch = get_effective_samples_per_minibatch(
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/multipack_sampler.py", line 78, in get_effective_samples_per_minibatch
[rank0]:     batches = sampler.generate_batches()
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/instructlab/venv/lib64/python3.11/site-packages/instructlab/training/multipack_sampler.py", line 398, in generate_batches
[rank0]:     batches, total_used, total_slots = allocate(
[rank0]:                                        ^^^^^^^^^
[rank0]: OverflowError: int too big to convert
E1029 20:12:21.122000 140022553749312 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 14529) of binary: /home/user/instructlab/venv/bin/python3.11
~~~

In my test, using  ` --pipeline full` and ` --device cpu`  works fine: 
~~~
ilab model train --pipeline full --device cpu --data-path /home/user/.local/share/instructlab/datasets/skills_train_msgs_2024-10-29T16_52_10.jsonl
~~~

**Comment by apcameron** [comment]
I get the same error with Instructlab 0.21.0

**Comment by apcameron** [comment]
@cdoern Are there any workarounds or fixes for this bug?

**Comment by apcameron** [comment]
WorkAround:
Change effective_batch_size: 64 in config.yaml to a lower number
I found effective_batch_size: 16 Works for my GPU

**Comment by shaneboulden** [comment]
Thanks @apcameron, updating the effective_batch_size fixed this issue for me. I'll close this now.
