### ISSUE TITLE
ilab data generate causing exceptions on serve

### ISSUE THREAD

**Issue by prestist** [instructlab/instructlab#2563]
**Describe the bug**

When running Ilab data generate assertion errors and Exceptions present them selves while watching the std out. 

**To Reproduce**
1. Python 3.11.6 installed
2. ilab serve --model-path ~/.cache/instructlab/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf
3. ilab data generate 
```
ilab model serve --model-path ~/.cache/instructlab/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf
INFO 2024-10-31 10:09:42,037 instructlab.model.serve:136: Using model '/Users/steven/.cache/instructlab/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf' with -1 gpu-layers and 4096 max context size.
INFO 2024-10-31 10:09:42,037 instructlab.model.serve:140: Serving model '/Users/steven/.cache/instructlab/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf' with llama-cpp
INFO 2024-10-31 10:09:42,324 instructlab.model.backends.llama_cpp:232: Replacing chat template:
 {% for message in messages %}
{% if message['role'] == 'user' %}
{{ '<|user|>
' + message['content'] }}
{% elif message['role'] == 'system' %}
{{ '<|system|>
' + message['content'] }}
{% elif message['role'] == 'assistant' %}
{{ '<|assistant|>
' + message['content'] + eos_token }}
{% endif %}
{% if loop.last and add_generation_prompt %}
{{ '<|assistant|>' }}
{% endif %}
{% endfor %}
INFO 2024-10-31 10:09:42,326 instructlab.model.backends.llama_cpp:189: Starting server process, press CTRL+C to shutdown server...
INFO 2024-10-31 10:09:42,326 instructlab.model.backends.llama_cpp:190: After application startup complete see http://127.0.0.1:8000/docs for API.
ERROR 2024-10-31 10:09:57,595 instructlab.model.serve:0: Exception:
ERROR 2024-10-31 10:09:58,058 instructlab.model.serve:0: Traceback (most recent call last):
  File "/Users/steven/instructlab/venv/lib/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steven/instructlab/venv/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steven/instructlab/venv/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steven/instructlab/venv/lib/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception:
ERROR 2024-10-31 10:09:58,929 instructlab.model.serve:0: Traceback (most recent call last):
  File "/Users/steven/instructlab/venv/lib/python3.11/site-packages/llama_cpp/server/errors.py", line 171, in custom_route_handler
    response = await original_route_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steven/instructlab/venv/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steven/instructlab/venv/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steven/instructlab/venv/lib/python3.11/site-packages/llama_cpp/server/app.py", line 264, in create_completion
    assert len(body.prompt) <= 1
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception:

```
And I don't seem to see progress on data generation.

**Expected behavior**

I expected data generation with no exceptions presented on the server.

**Device Info (please complete the following information):**
 - Hardware Specs: M1 pro with 32gb
 - OS Version: [e.g. Mac OS 14.6 (23G80)]
 - Python Version: Python 3.11.6
 - InstructLab Version: 
 ```
sys.version: 3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)]
sys.platform: darwin
os.name: posix
platform.release: 23.6.0
platform.machine: arm64
platform.node: Stevens-MacBook-Pro.local
platform.python_version: 3.11.6
platform.cpu_brand: Apple M1 Pro
instructlab.version: 0.19.4
instructlab-dolomite.version: 0.1.1
instructlab-eval.version: 0.3.1
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.4.1
instructlab-sdg.version: 0.3.2
instructlab-training.version: 0.5.5
torch.version: 2.3.1
torch.backends.cpu.capability: NO AVX
torch.version.cuda: None
torch.version.hip: None
torch.cuda.available: False
torch.backends.cuda.is_built: False
torch.backends.mps.is_built: True
torch.backends.mps.is_available: True
llama_cpp_python.version: 0.2.79
llama_cpp_python.supports_gpu_offload: True
 ```

**Additional context**
I initally tried it with my taxonamy but then decided to use the example in the readme found [here](https://github.com/instructlab/taxonomy?tab=readme-ov-file#knowledge-yaml-examples). 

Both return positive 

```
ilab taxonomy diff
knowledge/technology/coreos/butane/fcos/v1.5.0/qna.yaml
Taxonomy in /Users/steven/.local/share/instructlab/taxonomy is valid :)
```

**Comment by bjhargrave** [comment]
This is a dup of https://github.com/instructlab/instructlab/issues/1748

**Comment by prestist** [comment]
Thank you @bjhargrave , Did not see that one. So from reading SDG is working; I am just getting some noise ?

**Comment by bjhargrave** [comment]
Closing as a duplicate.
