### ISSUE TITLE
KeyError: 'messages' with ilab model train --data-path......

### ISSUE THREAD

**Issue by Forest-Person** [instructlab/instructlab#2600]
**Describe the bug**
ilab model train

**To Reproduce**
1. Go to ilab cli and attempt ilab model train command

4. See error:
5. (instructLab) permahuman@fedora:~/Desktop/eaWorks/taxonomy$ ilab model train --data-path "/home/permahuman/Desktop/eaWorks/taxonomy/generated/train_granite-3.0-3b-a800m-instruct-Q4_K_M_2024-11-07T11_42_49.jsonl"
LoRA is disabled (rank=0), ignoring all additional LoRA args
INFO 2024-11-09 01:12:39,911 numexpr.utils:161: NumExpr defaulting to 8 threads.
INFO 2024-11-09 01:12:40,032 datasets:59: PyTorch version 2.4.1 available.
 data arguments are:
{"data_path":"/home/permahuman/Desktop/eaWorks/taxonomy/generated/train_granite-3.0-3b-a800m-instruct-Q4_K_M_2024-11-07T11_42_49.jsonl","data_output_path":"/home/permahuman/.local/share/instructlab/internal","max_seq_len":4096,"model_path":"instructlab/granite-7b-lab","chat_tmpl_path":"/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/instructlab/training/chat_templates/ibm_generic_tmpl.py","num_cpu_procs":16}
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
INFO 2024-11-09 01:12:43,416 root:617: Special tokens: eos: [32000], pad: [32001], bos: [32005], system: [32004], user: [32002], assistant: [32003]
tokenizing the dataset with instructlab/granite-7b-lab tokenizer...
Map (num_proc=16):   0%|                                                                                                                                     | 0/101 [00:00<?, ? examples/s]
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/utils/py_utils.py", line 678, in _write_generator_to_queue
    for i, result in enumerate(func(**kwargs)):
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3528, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3427, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/instructlab/training/data_process.py", line 259, in <lambda>
    "input_ids": tokenizer.apply_chat_template(x["messages"], tokenize=True)
                                               ~^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/formatting/formatting.py", line 277, in __getitem__
    value = self.data[key]
            ~~~~~~~~~^^^^^
KeyError: 'messages'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/permahuman/Desktop/eaWorks/instructLab/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/instructlab/clickext.py", line 319, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/instructlab/cli/model/train.py", line 472, in train
    full_train.train(train_args=train_args, device=device)
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/instructlab/model/full_train.py", line 42, in train
    dp.main(
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/instructlab/training/data_process.py", line 257, in main
    data_with_input_ids = data.map(
                          ^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 602, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3259, in map
    for rank, done, content in iflatmap_unordered(
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/utils/py_utils.py", line 718, in iflatmap_unordered
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/utils/py_utils.py", line 718, in <listcomp>
    [async_result.get(timeout=0.05) for async_result in async_results]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/multiprocess/pool.py", line 774, in get
    raise self._value
KeyError: 'messages'


**Expected behavior**
I am ready to try and test run a model train with some of my generated data. Why would the data expect a messages key and not be provided in the generated data?



**Device Info (please complete the following information):**
 - intel core i7
 - Fedora Linux 41
 - Python Version: Python 3.11.10

 - InstructLab Version: ilab, version 0.20.1


p.s. stoked for the llama-cpp merge so we can start working with the smaller granite models and llama 3.2 1b and 3.2 3b. Thanks for all you do on this repo guys.

**Comment by Forest-Person** [comment]
> **Describe the bug** ilab model train
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to ilab cli and attempt ilab model train command
> 2. See error:
> 3. (instructLab) permahuman@fedora:~/Desktop/eaWorks/taxonomy$ ilab model train --data-path "/home/permahuman/Desktop/eaWorks/taxonomy/generated/train_granite-3.0-3b-a800m-instruct-Q4_K_M_2024-11-07T11_42_49.jsonl"
>    LoRA is disabled (rank=0), ignoring all additional LoRA args
>    INFO 2024-11-09 01:12:39,911 numexpr.utils:161: NumExpr defaulting to 8 threads.
>    INFO 2024-11-09 01:12:40,032 datasets:59: PyTorch version 2.4.1 available.
>    data arguments are:
>    {"data_path":"/home/permahuman/Desktop/eaWorks/taxonomy/generated/train_granite-3.0-3b-a800m-instruct-Q4_K_M_2024-11-07T11_42_49.jsonl","data_output_path":"/home/permahuman/.local/share/instructlab/internal","max_seq_len":4096,"model_path":"instructlab/granite-7b-lab","chat_tmpl_path":"/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/instructlab/training/chat_templates/ibm_generic_tmpl.py","num_cpu_procs":16}
>    You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in [⚠️⚠️[`T5Tokenize`] Fix T5 family tokenizers⚠️⚠️ huggingface/transformers#24565](https://github.com/huggingface/transformers/pull/24565) - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
>    INFO 2024-11-09 01:12:43,416 root:617: Special tokens: eos: [32000], pad: [32001], bos: [32005], system: [32004], user: [32002], assistant: [32003]
>    tokenizing the dataset with instructlab/granite-7b-lab tokenizer...
>    Map (num_proc=16):   0%|                                                                                                                                     | 0/101 [00:00<?, ? examples/s]
>    multiprocess.pool.RemoteTraceback:
>    """
>    Traceback (most recent call last):
>    File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/multiprocess/pool.py", line 125, in worker
>    result = (True, func(*args, **kwds))
>    ^^^^^^^^^^^^^^^^^^^
>    File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/utils/py_utils.py", line 678, in _write_generator_to_queue
>    for i, result in enumerate(func(**kwargs)):
>    File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3528, in _map_single
>    example = apply_function_on_filtered_inputs(example, i, offset=offset)
>    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3427, in apply_function_on_filtered_inputs
>    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
>    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/instructlab/training/data_process.py", line 259, in 
>    "input_ids": tokenizer.apply_chat_template(x["messages"], tokenize=True)
>    ~^^^^^^^^^^^^
>    File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/formatting/formatting.py", line 277, in **getitem**
>    value = self.data[key]
>    ~~~~~~~~~^^^^^
>    KeyError: 'messages'
>    """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/permahuman/Desktop/eaWorks/instructLab/bin/ilab", line 8, in sys.exit(ilab()) ^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/core.py", line 1157, in **call** return self.main(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/core.py", line 1078, in main rv = self.invoke(ctx) ^^^^^^^^^^^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/core.py", line 783, in invoke return __callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func return f(get_current_context(), *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/instructlab/clickext.py", line 319, in wrapper return f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/instructlab/cli/model/train.py", line 472, in train full_train.train(train_args=train_args, device=device) File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/instructlab/model/full_train.py", line 42, in train dp.main( File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/instructlab/training/data_process.py", line 257, in main data_with_input_ids = data.map( ^^^^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 602, in wrapper out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 567, in wrapper out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3259, in map for rank, done, content in iflatmap_unordered( File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/utils/py_utils.py", line 718, in iflatmap_unordered [async_result.get(timeout=0.05) for async_result in async_results] File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/datasets/utils/py_utils.py", line 718, in [async_result.get(timeout=0.05) for async_result in async_results] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/permahuman/Desktop/eaWorks/instructLab/lib/python3.11/site-packages/multiprocess/pool.py", line 774, in get raise self._value KeyError: 'messages'
> 
> **Expected behavior** I am ready to try and test run a model train with some of my generated data. Why would the data expect a messages key and not be provided in the generated data?
> 
> **Device Info (please complete the following information):**
> 
> * intel core i7
> * Fedora Linux 41
> * Python Version: Python 3.11.10
> * InstructLab Version: ilab, version 0.20.1


I upgraded instruct lab and the problem was solved.

**Comment by Forest-Person** [comment]
A simple "pip install instructlab  --force-reinstall --upgrade" solved the problem.
