### ISSUE TITLE
Error while training models other than the default model (merlinite-7b-lab-Q4_K_M.gguf)

### ISSUE THREAD

**Issue by amrita-rajput** [instructlab/instructlab#2601]
**Describe the bug**
I'm unable to train models other than the default model (merlinite-7b-lab-Q4_K_M.gguf). When attempting to train the model mistral-7b-instruct-v0.2.Q4_K_M.gguf, I encounter an error.

**To Reproduce**

1. Run the following command to initiate training on the mistral-7b-instruct-v0.2.Q4_K_M.gguf model:

`ilab model train --data-path /Users/amritarajput/.local/share/instructlab/datasets/skills_train_msgs_2024-11-08T13_31_26.jsonl --model-path /Users/amritarajput/.cache/instructlab/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf`

2. See error message:
```

(.venv) amritarajput@Amritas-MacBook-Pro models % ilab model train --data-path /Users/amritarajput/.local/share/instructlab/datasets/skills_train_msgs_2024-11-08T13_31_26.jsonl --model-path /Users/amritarajput/.cache/instructlab/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf 
LoRA is disabled (rank=0), ignoring all additional LoRA args
INFO 2024-11-08 14:57:58,139 numexpr.utils:161: NumExpr defaulting to 10 threads.
INFO 2024-11-08 14:57:58,232 datasets:59: PyTorch version 2.4.1 available.
 data arguments are:
{"data_path":"/Users/amritarajput/.local/share/instructlab/datasets/skills_train_msgs_2024-11-08T13_31_26.jsonl","data_output_path":"/Users/amritarajput/.local/share/instructlab/internal","max_seq_len":4096,"model_path":"/Users/amritarajput/.cache/instructlab/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf","chat_tmpl_path":"/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/instructlab/training/chat_templates/ibm_generic_tmpl.py","num_cpu_procs":16}
Traceback (most recent call last):
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/Users/amritarajput/.cache/instructlab/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/amritarajput/Desktop/ilab_all/.venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/instructlab/clickext.py", line 319, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/instructlab/cli/model/train.py", line 472, in train
    full_train.train(train_args=train_args, device=device)
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/instructlab/model/full_train.py", line 42, in train
    dp.main(
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/instructlab/training/data_process.py", line 228, in main
    tokenizer = setup_tokenizer(args.model_path, SPECIAL_TOKENS, CHAT_TEMPLATE)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/instructlab/training/tokenizer_utils.py", line 40, in setup_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, fast_tokenizer=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 857, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 689, in get_tokenizer_config
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "/Users/amritarajput/Desktop/ilab_all/.venv/lib/python3.11/site-packages/transformers/utils/hub.py", line 469, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '/Users/amritarajput/.cache/instructlab/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```

**Expected behavior**
The model mistral-7b-instruct-v0.2.Q4_K_M.gguf should successfully start training with the provided data path.
<img width="1728" alt="Screenshot 2024-11-08 at 3 01 57 PM" src="https://github.com/user-attachments/assets/862cc411-7855-4fad-9b23-613b3b93f6dc">

**Device Info (please complete the following information):**

1. Hardware Specs: Apple M1 Chip
3. Python Version: 3.11.5
4. InstructLab Version: 0.20.1

**Comment by jaideepr97** [comment]
@amrita-rajput the model you supply needs to be a safetensors model. Training with GGUF models is not supported. GGUF models are only used for inference (i.e, you can serve a GGUF model and chat with it or use it as a teacher model to do data generation against)
