### ISSUE TITLE
ilab, version 0.21.0 --help flag fails for most commands

### ISSUE THREAD

**Issue by gshipley** [instructlab/instructlab#2683]
**Describe the bug**
ilab version 0.21.0 
python 3.11.9

Running any of the main ilab commands / sub commands with the --help fails for some commands

**To Reproduce**
python3.11 -m venv venv
pip install instructlab
ilab config init
ilab model download --help
^ works
ilab model chat --help
^ fails

**Expected behavior**
You get the help.

**Screenshots**
$ ilab model download --help
Usage: ilab model download [OPTIONS]

  Downloads model from a specified repository

Options:
  -rp, --repository TEXT  Hugging Face or OCI repository of the model to
                          download.  [default: instructlab/granite-7b-lab-
                          GGUF, instructlab/merlinite-7b-lab-GGUF,
                          TheBloke/Mistral-7B-Instruct-v0.2-GGUF]
  -rl, --release TEXT     The revision of the model to download - e.g. a
                          branch, tag, or commit hash for Hugging Face
                          repositories and tag or commit hash for OCI
                          repositories.  [default: main, main, main]
  --filename TEXT         Name of the model file to download from the Hugging
                          Face repository.  [default: (The default model
                          location in the instructlab data directory.)]
  --model-dir TEXT        The local directory to download the model files
                          into.  [default: (The default system model location
                          store, located in the data directory.)]
  --hf-token TEXT         User access token for connecting to the Hugging Face
                          Hub.
  --help                  Show this message and exit.

-----------
$ ilab model chat --help
   
Traceback (most recent call last):
  File "/Users/gshipley/code/v21/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 1300, in show_help
    echo(ctx.get_help(), color=ctx.color)
         ^^^^^^^^^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 704, in get_help
    return self.command.get_help(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 1325, in get_help
    self.format_help(ctx, formatter)
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 1358, in format_help
    self.format_options(ctx, formatter)
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/click/core.py", line 1382, in format_options
    rv = param.get_help_record(ctx)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/instructlab/clickext.py", line 170, in get_help_record
    description, default_value = get_default_and_description(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/instructlab/clickext.py", line 370, in get_default_and_description
    default_value = field.get_default(call_default_factory=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gshipley/code/v21/venv/lib/python3.11/site-packages/pydantic/fields.py", line 596, in get_default
    raise ValueError("'validated_data' must be provided if 'call_default_factory' is True.")
ValueError: 'validated_data' must be provided if 'call_default_factory' is True.

**Device Info (please complete the following information):**
ilab, version 0.21.0
Python 3.11.9

ilab system info:
Platform:
  sys.version: 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]
  sys.platform: darwin
  os.name: posix
  platform.release: 24.2.0
  platform.machine: arm64
  platform.node: gshipley-mac
  platform.python_version: 3.11.9
  platform.cpu_brand: Apple M3 Max
  memory.total: 128.00 GB
  memory.available: 94.50 GB
  memory.used: 32.61 GB

InstructLab:
  instructlab.version: 0.21.0
  instructlab-dolomite.version: 0.2.0
  instructlab-eval.version: 0.4.1
  instructlab-quantize.version: 0.1.0
  instructlab-schema.version: 0.4.1
  instructlab-sdg.version: 0.6.0
  instructlab-training.version: 0.6.1

Torch:
  torch.version: 2.4.1
  torch.backends.cpu.capability: NO AVX
  torch.version.cuda: None
  torch.version.hip: None
  torch.cuda.available: False
  torch.backends.cuda.is_built: False
  torch.backends.mps.is_built: True
  torch.backends.mps.is_available: True

llama_cpp_python:
  llama_cpp_python.version: 0.2.79
  llama_cpp_python.supports_gpu_offload: True

**Additional context**

**Comment by nathan-weinberg** [comment]
@cdoern and I are looking into this with @gshipley and @taylorjordanNC, will update here

**Comment by nathan-weinberg** [comment]
This seems to have been an installation quirk, I think we should action out from this some updates to the upgrade section of our README

**Comment by gshipley** [comment]
pip install --force-reinstall --no-cache-dir instructlab

Fixes the issue for anyone who runs into this in the future.
