### ISSUE TITLE
`test_bind_port` consistently failing on MacOS runner

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/instructlab#2753]
Logs can be seen here (job is `test: 3.11 on macos-latest`): https://github.com/instructlab/instructlab/actions/workflows/test.yml 

Example output:
```
2024-12-06T15:10:21.5870320Z Traceback (most recent call last):
2024-12-06T15:10:21.5870780Z   File "/Users/runner/work/instructlab/instructlab/.tox/py311-functional/bin/ilab", line 8, in <module>
2024-12-06T15:10:21.5871310Z     sys.exit(ilab())
2024-12-06T15:10:21.5871550Z              ^^^^^^
2024-12-06T15:10:21.5872170Z   File "/Users/runner/work/instructlab/instructlab/.tox/py311-functional/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
2024-12-06T15:10:21.5872800Z     return self.main(*args, **kwargs)
2024-12-06T15:10:21.5873200Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-06T15:10:21.5873690Z   File "/Users/runner/work/instructlab/instructlab/.tox/py311-functional/lib/python3.11/site-packages/click/core.py", line 1078, in main
2024-12-06T15:10:21.5874140Z     rv = self.invoke(ctx)
2024-12-06T15:10:21.5874330Z          ^^^^^^^^^^^^^^^^
2024-12-06T15:10:21.5875000Z   File "/Users/runner/work/instructlab/instructlab/.tox/py311-functional/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
2024-12-06T15:10:21.5875640Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2024-12-06T15:10:21.5876080Z                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-06T15:10:21.5876880Z   File "/Users/runner/work/instructlab/instructlab/.tox/py311-functional/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
2024-12-06T15:10:21.5877490Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2024-12-06T15:10:21.5878200Z                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-06T15:10:21.5878840Z   File "/Users/runner/work/instructlab/instructlab/.tox/py311-functional/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
2024-12-06T15:10:21.5912920Z     return ctx.invoke(self.callback, **ctx.params)
2024-12-06T15:10:21.5913250Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-06T15:10:21.5913940Z   File "/Users/runner/work/instructlab/instructlab/.tox/py311-functional/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2024-12-06T15:10:21.5914480Z     return __callback(*args, **kwargs)
2024-12-06T15:10:21.5914850Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-06T15:10:21.5915390Z   File "/Users/runner/work/instructlab/instructlab/.tox/py311-functional/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
2024-12-06T15:10:21.5915940Z     return f(get_current_context(), *args, **kwargs)
2024-12-06T15:10:21.5917180Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-06T15:10:21.5917750Z   File "/Users/runner/work/instructlab/instructlab/.tox/py311-functional/lib/python3.11/site-packages/instructlab/clickext.py", line 323, in wrapper
2024-12-06T15:10:21.5918360Z     return f(*args, **kwargs)
2024-12-06T15:10:21.5918580Z            ^^^^^^^^^^^^^^^^^^
2024-12-06T15:10:21.5919220Z   File "/Users/runner/work/instructlab/instructlab/.tox/py311-functional/lib/python3.11/site-packages/instructlab/cli/model/serve.py", line 104, in serve
2024-12-06T15:10:21.5919760Z     serve_backend(
2024-12-06T15:10:21.5920450Z   File "/Users/runner/work/instructlab/instructlab/.tox/py311-functional/lib/python3.11/site-packages/instructlab/model/serve_backend.py", line 51, in serve_backend
2024-12-06T15:10:21.5921180Z     raise ValueError(f"Failed to determine backend: {e}") from e
2024-12-06T15:10:21.5922150Z ValueError: Failed to determine backend: Cannot determine which backend to use: The model file /var/folders/0w/4z5l9vds32nbkz7l22n8j6s99990gn/T/tmp.cFGEzcxi2k/.cache/instructlab/models/granite-7b-lab-Q4_K_M.gguf is not a GGUF format nor a directory containing huggingface safetensors files. Cannot determine which backend to use. 
2024-12-06T15:10:21.5923360Z Please use a GGUF file for llama-cpp or a directory containing huggingface safetensors files for vllm. 
2024-12-06T15:10:21.5923840Z Note that vLLM is only supported on Linux.
```

**Comment by courtneypacheco** [comment]
I will work on this and try to identify a solution.
