### ISSUE TITLE
Issue while creating Synthetic Data Creation 

### ISSUE THREAD

**Issue by kushalpuri0817** [instructlab/instructlab#2834]
**Describe the bug**
Getting multiple errors while generating synthetic data "ilab generate" command
**To Reproduce**

**Expected behavior**
Synthetic data generation should go fine.

**Screenshots**

Generating synthetic data using 'models/merlinite-7b-lab-Q4_K_M.gguf' model, taxonomy:'taxonomy' against http://*********:10261/v1 server
Cannot find prompt.txt. Using default prompt depending on model-family.
Traceback (most recent call last):
  File "/Users/tanvimaira/Documents/demo/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/Users/tanvimaira/Documents/demo/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanvimaira/Documents/demo/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/tanvimaira/Documents/demo/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanvimaira/Documents/demo/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanvimaira/Documents/demo/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanvimaira/Documents/demo/venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanvimaira/Documents/demo/venv/lib/python3.12/site-packages/instructlab/data/generate.py", line 198, in generate
    generate_data(
  File "/Users/tanvimaira/Documents/demo/venv/lib/python3.12/site-packages/instructlab/data/generator/generate_data.py", line 407, in generate_data
    len(seed_example["instruction"])
TypeError: object of type 'NoneType' has no len()

**Device Info (please complete the following information):**
 - Hardware Specs: [e.g. Apple M2 Pro Chip, 16 GB Memory, etc.] : Apple M3 16 GB
 - OS Version: [e.g. Mac OS 14.4.1, Fedora Linux 40] : 15.2 (24C101)
 - Python Version: [output of `python --version`] : python 3.12
 - InstructLab Version: [output of `ilab system info`] :  ilab, version 0.17.2

**Additional context**
I am following this video to generate the synthetic data
https://www.youtube.com/watch?v=Jb5dh3Uzdbw&t=185s

**Comment by reidliu41** [comment]
could you please change the `python version` first?
https://github.com/instructlab/instructlab?tab=readme-ov-file#-requirements

**Comment by ktam3** [comment]
@kushalpuri0817 - let us know if updating the python version fixed the issue or if it still persists, thanks.

**Comment by hdcpereira** [comment]
I'm having the same issue and I'm on python version 3.11. 

```
instructlab.version: 0.17.2
sys.version: 3.11.11 (main, Dec  3 2024, 17:20:40) [Clang 16.0.0 (clang-1600.0.26.4)]
sys.platform: darwin
os.name: posix
platform.release: 24.3.0
platform.machine: x86_64
torch.version: 2.2.2
torch.backends.cpu.capability: NO AVX
torch.version.cuda: None
torch.version.hip: None
torch.cuda.available: False
torch.backends.cuda.is_built: False
torch.backends.mps.is_built: True
torch.backends.mps.is_available: True
llama_cpp_python.version: 0.2.75
llama_cpp_python.supports_gpu_offload: True
```

**Comment by ktam3** [comment]
@hdcpereira - could you update to the most recent version of ilab and see if this is still an issue?
