### ISSUE TITLE
llama_cpp/libllama.so not found

### ISSUE THREAD

**Issue by RobertGreenberg** [instructlab/instructlab#2842]
**Describe the bug**
When trying to install InstructLab on my M2 Max, I can successfully install and initialize, but when I try to run ```ilab chat```, I get this error: 

```FileNotFoundError: Shared library with base name '/home/developer/miniconda3/envs/labEnv/lib/python3.11/site-packages/llama_cpp/libllama.so' not found```

Output: 
```File "/Users/RobertGreenberg/miniconda3/envs/native/bin/ilab", line 8, in <module>
    sys.exit(ilab())
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/instructlab/clickext.py", line 323, in wrapper
    return f(*args, **kwargs)
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/instructlab/model/chat.py", line 232, in chat
    backend_instance = backends.select_backend(
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/instructlab/model/backends/backends.py", line 124, in select_backend
    from .llama_cpp import Server as llama_cpp_server
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/instructlab/model/backends/llama_cpp.py", line 14, in <module>
    from llama_cpp import llama_chat_format, llama_token_get_text
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/llama_cpp/llama_cpp.py", line 83, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/llama_cpp/llama_cpp.py", line 74, in _load_shared_library
    raise FileNotFoundError(
FileNotFoundError: Shared library with base name '/home/developer/miniconda3/envs/labEnv/lib/python3.11/site-packages/llama_cpp/libllama.so' not found
```

**Screenshots**

**Device Info (please complete the following information):**
 - Hardware Specs: Apple M2 Max Chip
 - OS Version: Mac OS 15.1.1
 - Python Version: Python Version 3.10
 - InstructLab Version: instructlab-0.22.1

Any help would be appreciated!

**Comment by reidliu41** [comment]
```
 File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10/site-packages/llama_cpp/llama_cpp.py", line 83, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "/Users/RobertGreenberg/miniconda3/envs/native/lib/python3.10<<<<<<<<<</site-packages/llama_cpp/llama_cpp.py", line 74, in _load_shared_library
    raise FileNotFoundError(
FileNotFoundError: Shared library with base name '/home/developer/miniconda3/envs/labEnv/lib/python3.11 <<<<<<------/site-packages/llama_cpp/libllama.so' not found
```
Looks like the env is using the mix python version, it is possible to only use `python3.11` to setup the venv ?? And then install.

**Comment by RobertGreenberg** [comment]
Will try to create a new venv w/ Python 3.10 only. ilab only supports <= 3.10 afaik

**Comment by RobertGreenberg** [comment]
Set up a new env w/ 3.10 and still getting the same error. How can I delete ```'/home/developer/miniconda3/envs/labEnv/lib/python3.11/site-packages/llama_cpp/libllama.so'``` to look in 3.10 lib folder?

**Comment by reidliu41** [comment]
```
Python 3.10 or Python 3.11

📋 Python 3.12 is currently not supported. Some InstructLab dependencies don't work on Python 3.12
```
Python3.11 should be better.
Seems related to `miniconda3 `, could you please try without `it`?

**Comment by RobertGreenberg** [comment]
```Traceback (most recent call last):
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/instructlab/clickext.py", line 323, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/instructlab/model/chat.py", line 232, in chat
    backend_instance = backends.select_backend(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/instructlab/model/backends/backends.py", line 124, in select_backend
    from .llama_cpp import Server as llama_cpp_server
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/instructlab/model/backends/llama_cpp.py", line 14, in <module>
    from llama_cpp import llama_chat_format, llama_token_get_text
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/llama_cpp/llama_cpp.py", line 83, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/RobertGreenberg/Documents/InstructLab/venv/lib/python3.11/site-packages/llama_cpp/llama_cpp.py", line 74, in _load_shared_library
    raise FileNotFoundError(
FileNotFoundError: Shared library with base name '/home/developer/miniconda3/envs/labEnv/lib/python3.11/site-packages/llama_cpp/libllama.so' not found
```

Same issue with a new venv created and it's all on python 3.11 now.

**Comment by RobertGreenberg** [comment]
miniconda messed it all up, I unset my LD_LIBRARY_PATH and LLAMA_CPP_LIB to the new venv and got it working!
