### ISSUE TITLE
Investigate training with device_map="auto" for GPUs with less memory

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#610]
Accelerate has an option `device_map` to distribute layers of a model across CPU, multiple GPUs, and disk. It automatically detects free memory on devices and assigns layers accordingly. This could be an option to allow users to train a model on GPU that do not have sufficient VRAM to fit the entire model. The concept is explained here https://huggingface.co/docs/accelerate/concept_guides/big_model_inference

```python
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype="auto",
        quantization_config=bnb_config,
        config=config,
        trust_remote_code=True,
        low_cpu_mem_usage=True,
        device_map="auto",
        # force max memory to emulate card with less memory
        max_memory={0: "10GiB", "cpu": "30GiB"},
    )
```

My device map is:

```python
>>> json.dumps(model.hf_device_map, indent=2)
{
  "model.embed_tokens": 0,
  "model.layers.0": 0,
  "model.layers.1": 0,
  "model.layers.2": 0,
  "model.layers.3": 0,
  "model.layers.4": 0,
  "model.layers.5": 0,
  "model.layers.6": 0,
  "model.layers.7": 0,
  "model.layers.8": 0,
  "model.layers.9": 0,
  "model.layers.10": 0,
  "model.layers.11": 0,
  "model.layers.12": 0,
  "model.layers.13": 0,
  "model.layers.14": 0,
  "model.layers.15": 0,
  "model.layers.16": 0,
  "model.layers.17": 0,
  "model.layers.18": 0,
  "model.layers.19": 0,
  "model.layers.20": 0,
  "model.layers.21": 0,
  "model.layers.22": "cpu",
  "model.layers.23": "cpu",
  "model.layers.24": "cpu",
  "model.layers.25": "cpu",
  "model.layers.26": "cpu",
  "model.layers.27": "cpu",
  "model.layers.28": "cpu",
  "model.layers.29": "cpu",
  "model.layers.30": "cpu",
  "model.layers.31": "cpu",
  "model.norm": "cpu",
  "lm_head": "cpu"
}
```

However [SFTrainer](https://huggingface.co/docs/trl/sft_trainer) is failing with an exception that I do not understand. It appears that it cannot move "meta tensor" between GPU and CPU device (whatever that means).
```
Traceback (most recent call last):
  File "/home/heimes/redhat/ai/instruct-lab/cli/cli/train/linux_train.py", line 347, in <module>
    main()
  File "/home/heimes/redhat/ai/instruct-lab/cli/cli/train/linux_train.py", line 304, in main
    trainer = SFTTrainer(
              ^^^^^^^^^^^
  File "/opt/rocm-venv/lib64/python3.12/site-packages/trl/trainer/sft_trainer.py", line 299, in __init__
    super().__init__(
  File "/opt/rocm-venv/lib64/python3.12/site-packages/transformers/trainer.py", line 489, in __init__
    self._move_model_to_device(model, args.device)
  File "/opt/rocm-venv/lib64/python3.12/site-packages/transformers/trainer.py", line 730, in _move_model_to_device
    model = model.to(device)
            ^^^^^^^^^^^^^^^^
  File "/opt/rocm-venv/lib64/python3.12/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/rocm-venv/lib64/python3.12/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/rocm-venv/lib64/python3.12/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/rocm-venv/lib64/python3.12/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "/opt/rocm-venv/lib64/python3.12/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/opt/rocm-venv/lib64/python3.12/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Cannot copy out of meta tensor; no data!
```

My setup:
* Fedora 39 Kernel, Fedora 40 toolbox
* PyTorch 2.2.1+rocm5.7
* no flash attention, as I'm unable to build it for AMD ROCm.
* AMD Radeon RX 7900 XT (20 GiB)

**Comment by nathan-weinberg** [comment]
@bbrowning @tiran is this issue still relevant or can it be closed?

**Comment by bbrowning** [comment]
I believe this issue can be closed, as `device_map="auto"` is only for inference and cannot be used in training, as was mentioned earlier upthread.

**Comment by nathan-weinberg** [comment]
@bbrowning thanks, I will close it for now and we can reopen later if necessary!
