### ISSUE TITLE
Functional tests fail with `Aborted!` message when calling `ilab chat` (RHEL 8.6, Python 3.9)

### ISSUE THREAD

**Issue by booxter** [instructlab/instructlab#947]
Functional tests fail for me while waiting for the context length error in chat log.

```
+2024-04-19 22:53:59 ./scripts/functional-tests.sh:126: test_ctx_size(): timeout 100 bash -c '
        until grep -q "Message too large for context size." "$TEST_CTX_SIZE_LAB_CHAT_LOG_FILE"; do
        echo "waiting for chat error"
        sleep 1
    done
'
waiting for chat error
waiting for chat error
waiting for chat error
waiting for chat error
waiting for chat error
```

When I check the chat command log, I only see:

```
INFO 2024-04-19 22:06:54,675 _client.py:1026 HTTP Request: GET http://127.0.0.1:8000/v1/models "HTTP/1.1 200 OK"
Warning: Input is not a terminal (fd=0).
╭────────────────────────────────────────────────────── system ──────────────────────────────────────────────────────╮
│ Welcome to Chat CLI w/ MERLINITE-7B-LAB-Q4_K_M (type /h for help)                                                  │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Aborted!
```

I disabled `standalone_mode` for `click` command for `chat`, and here is the full exception hidden by the library:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/lib64/python3.9/selectors.py", line 193, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '0 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/prompt_toolkit/input/vt100.py", line 165, in _attached_input
    loop.add_reader(fd, callback_wrapper)
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 331, in add_reader
    self._add_reader(fd, callback, *args)
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 258, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/usr/lib64/python3.9/selectors.py", line 360, in register
    self._selector.register(key.fd, poller_events)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/instructlab/lab.py", line 633, in chat
    chat_cli(
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/instructlab/chat/chat.py", line 539, in chat_cli
    ccb.start_prompt(logger=logger)
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/instructlab/chat/chat.py", line 323, in start_prompt
    content = self.input.prompt(
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1026, in prompt
    return self.app.run(
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 1002, in run
    return asyncio.run(coro)
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 886, in run_async
    return await _run_async(f)
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 734, in _run_async
    with self.input.raw_mode(), self.input.attach(
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/prompt_toolkit/input/vt100.py", line 174, in _attached_input
    raise EOFError
EOFError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/bin/ilab", line 8, in <module>
    sys.exit(cli_wrap())
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/instructlab/lab.py", line 86, in cli_wrap
    return cli(standalone_mode=False)
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ihrachys/instruct-lab-gitlab/cli/.tox/functional/lib/python3.9/site-packages/click/core.py", line 1091, in main
    raise Abort() from e
click.exceptions.Abort
```

I was able to overcome the issue by switching from `ilab chat` to `ilab chat -qq` variant of the command.

A similar issue was reported in several other places, e.g.: https://github.com/commitizen-tools/commitizen-docker-image/issues/11

**Comment by nathan-weinberg** [comment]
@booxter is this still an issue?

**Comment by booxter** [comment]
@nathan-weinberg I don't know. I don't have access to rhel8.x machine anymore to double check. Maybe we don't care and can close it now. I will close if no one steps in in several days.

**Comment by nathan-weinberg** [comment]
@booxter python 3.9 is no longer supported anyway, so I'd be fine to close
